service: mysanggibu-backend
runtime: nodejs22
instance_class: F2
entrypoint: node dist/main.js

env_variables:
  NODE_ENV: "production"
  PORT: "8080"
  DB_TYPE: "postgres"
  DB_HOST: "/cloudsql/ts-back-nest-479305:asia-northeast3:geobuk-db"
  DB_PORT: "5432"
  DB_USER: "tsuser"
  DB_PASSWORD: "tsuser1234"
  DB_NAME: "geobukschool_prod"
  DB_SYNCHRONIZE: "false"
  DB_SCHEMA: "mysanggibu,hub,susi,jungsi"
  AUTH_JWT_SECRET: "04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1"
  AUTH_JWT_TOKEN_EXPIRES_IN: "7200000"
  AUTH_REFRESH_SECRET: "178235718923571923571925sda9sd90f821309sdfa0s9df802139458sdfasd09f78adsf785a9cvads"
  AUTH_REFRESH_TOKEN_EXPIRES_IN: "5184000000"
  IMP_KEY: "9840772778157981"
  IMP_SECRET: "N8Gb7jy1c34UMmCzcK5WIX5gnqiTr9MfitrpM0rY3vTQRvq4gv0Yt6fRwxKYHwdZZEpLFQJImDze8Zio"
  IMP_STORE_CODE: "MOIingip66"
  ALIGO_API_KEY: "mo5wdn7mk290x5cuoq8vu1q5splx4rny"
  ALIGO_USER_ID: "withjuno"
  ALIGO_SENDER_PHONE: "01025187139"
  ALIGO_TEST_MODE: "false"
  SENTRY_DSN: "https://447c782f7b8fe49649f93dce7efaf8f2@o4507769007505408.ingest.us.sentry.io/4507769070419968"
  SLACK_WEBHOOK: "https://hooks.slack.com/services/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"
  GCS_PROJECT_ID: "ts-back-nest-479305"
  GCS_BUCKET_NAME: "ts-back-nest-bk"
  GCS_PUBLIC_URL: "https://storage.googleapis.com/ts-back-nest-bk"

beta_settings:
  cloud_sql_instances: "ts-back-nest-479305:asia-northeast3:geobuk-db"

automatic_scaling:
  min_instances: 0
  max_instances: 3
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65

handlers:
  - url: /.*
    script: auto
    secure: always
# Sensitive env vars should be set via:
# gcloud app deploy --set-env-vars="DB_PASSWORD=xxx,AUTH_JWT_SECRET=xxx,..."
