/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ProductsIndexImport } from './routes/products/index'
import { Route as UsersLayoutImport } from './routes/users/_layout'
import { Route as SusiLayoutImport } from './routes/susi/_layout'
import { Route as OrderProductIdImport } from './routes/order/$productId'
import { Route as OfficerLayoutImport } from './routes/officer/_layout'
import { Route as JungsiLayoutImport } from './routes/jungsi/_layout'
import { Route as ExploreUniversityImport } from './routes/explore/university'
import { Route as ExploreRecruitmentUnitImport } from './routes/explore/recruitment-unit'
import { Route as ExploreAdmissionImport } from './routes/explore/admission'
import { Route as EvaluationLayoutImport } from './routes/evaluation/_layout'
import { Route as AuthResetPasswordImport } from './routes/auth/reset-password'
import { Route as AuthRegisterImport } from './routes/auth/register'
import { Route as AuthLoginImport } from './routes/auth/login'

// Create Virtual Routes

const UsersImport = createFileRoute('/users')()
const SusiImport = createFileRoute('/susi')()
const OfficerImport = createFileRoute('/officer')()
const JungsiImport = createFileRoute('/jungsi')()
const EvaluationImport = createFileRoute('/evaluation')()
const SusiIndexLazyImport = createFileRoute('/susi/')()
const JungsiIndexLazyImport = createFileRoute('/jungsi/')()
const EvaluationIndexLazyImport = createFileRoute('/evaluation/')()
const AnalysisIndexLazyImport = createFileRoute('/analysis/')()
const SusiSubjectLazyImport = createFileRoute('/susi/subject')()
const SusiNonsulLazyImport = createFileRoute('/susi/nonsul')()
const SusiComprehensiveLazyImport = createFileRoute('/susi/comprehensive')()
const OfficialGuideLazyImport = createFileRoute('/official/guide')()
const OfficialFaqLazyImport = createFileRoute('/official/faq')()
const JungsiCLazyImport = createFileRoute('/jungsi/c')()
const JungsiBLazyImport = createFileRoute('/jungsi/b')()
const JungsiALazyImport = createFileRoute('/jungsi/a')()
const ExploreEarlySubjectLazyImport = createFileRoute(
  '/explore/early-subject',
)()
const ExploreEarlyComprehensiveLazyImport = createFileRoute(
  '/explore/early-comprehensive',
)()
const ExplainServiceLazyImport = createFileRoute('/explain/service')()
const ExplainRefundLazyImport = createFileRoute('/explain/refund')()
const ExplainPrivacyLazyImport = createFileRoute('/explain/privacy')()
const AnalysisPerformanceLazyImport = createFileRoute('/analysis/performance')()
const AnalysisComparisonLazyImport = createFileRoute('/analysis/comparison')()
const naverRedirectLazyImport = createFileRoute('/(naver)/redirect')()
const OfficialNoticeIndexLazyImport = createFileRoute('/official/notice/')()
const UsersLayoutSchoolRecordLazyImport = createFileRoute(
  '/users/_layout/school-record',
)()
const UsersLayoutProfileLazyImport = createFileRoute('/users/_layout/profile')()
const UsersLayoutMockExamLazyImport = createFileRoute(
  '/users/_layout/mock-exam',
)()
const UsersLayoutAdditionalFileLazyImport = createFileRoute(
  '/users/_layout/additional-file',
)()
const SusiLayoutInterestLazyImport = createFileRoute('/susi/_layout/interest')()
const SusiLayoutCombinationLazyImport = createFileRoute(
  '/susi/_layout/combination',
)()
const OfficialNoticePostIdLazyImport = createFileRoute(
  '/official/notice/$postId',
)()
const OfficerLayoutProfileLazyImport = createFileRoute(
  '/officer/_layout/profile',
)()
const JungsiLayoutInterestLazyImport = createFileRoute(
  '/jungsi/_layout/interest',
)()
const JungsiLayoutCombinationLazyImport = createFileRoute(
  '/jungsi/_layout/combination',
)()
const EvaluationLayoutRequestLazyImport = createFileRoute(
  '/evaluation/_layout/request',
)()
const EvaluationLayoutListLazyImport = createFileRoute(
  '/evaluation/_layout/list',
)()
const EvaluationLayoutCompatibilityLazyImport = createFileRoute(
  '/evaluation/_layout/compatibility',
)()
const UsersLayoutPaymentIndexLazyImport = createFileRoute(
  '/users/_layout/payment/',
)()
const OfficerLayoutApplyIndexLazyImport = createFileRoute(
  '/officer/_layout/apply/',
)()
const EvaluationLayoutSelfIndexLazyImport = createFileRoute(
  '/evaluation/_layout/self/',
)()
const UsersLayoutPaymentIdLazyImport = createFileRoute(
  '/users/_layout/payment/$id',
)()
const OfficerLayoutApplyStudentIdLazyImport = createFileRoute(
  '/officer/_layout/apply/$studentId',
)()
const EvaluationLayoutSelfEditLazyImport = createFileRoute(
  '/evaluation/_layout/self/edit',
)()

// Create/Update Routes

const UsersRoute = UsersImport.update({
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const SusiRoute = SusiImport.update({
  path: '/susi',
  getParentRoute: () => rootRoute,
} as any)

const OfficerRoute = OfficerImport.update({
  path: '/officer',
  getParentRoute: () => rootRoute,
} as any)

const JungsiRoute = JungsiImport.update({
  path: '/jungsi',
  getParentRoute: () => rootRoute,
} as any)

const EvaluationRoute = EvaluationImport.update({
  path: '/evaluation',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SusiIndexLazyRoute = SusiIndexLazyImport.update({
  path: '/',
  getParentRoute: () => SusiRoute,
} as any).lazy(() => import('./routes/susi/index.lazy').then((d) => d.Route))

const JungsiIndexLazyRoute = JungsiIndexLazyImport.update({
  path: '/',
  getParentRoute: () => JungsiRoute,
} as any).lazy(() => import('./routes/jungsi/index.lazy').then((d) => d.Route))

const EvaluationIndexLazyRoute = EvaluationIndexLazyImport.update({
  path: '/',
  getParentRoute: () => EvaluationRoute,
} as any).lazy(() =>
  import('./routes/evaluation/index.lazy').then((d) => d.Route),
)

const AnalysisIndexLazyRoute = AnalysisIndexLazyImport.update({
  path: '/analysis/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/analysis/index.lazy').then((d) => d.Route),
)

const ProductsIndexRoute = ProductsIndexImport.update({
  path: '/products/',
  getParentRoute: () => rootRoute,
} as any)

const SusiSubjectLazyRoute = SusiSubjectLazyImport.update({
  path: '/subject',
  getParentRoute: () => SusiRoute,
} as any).lazy(() => import('./routes/susi/subject.lazy').then((d) => d.Route))

const SusiNonsulLazyRoute = SusiNonsulLazyImport.update({
  path: '/nonsul',
  getParentRoute: () => SusiRoute,
} as any).lazy(() => import('./routes/susi/nonsul.lazy').then((d) => d.Route))

const SusiComprehensiveLazyRoute = SusiComprehensiveLazyImport.update({
  path: '/comprehensive',
  getParentRoute: () => SusiRoute,
} as any).lazy(() =>
  import('./routes/susi/comprehensive.lazy').then((d) => d.Route),
)

const OfficialGuideLazyRoute = OfficialGuideLazyImport.update({
  path: '/official/guide',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/official/guide.lazy').then((d) => d.Route),
)

const OfficialFaqLazyRoute = OfficialFaqLazyImport.update({
  path: '/official/faq',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/official/faq.lazy').then((d) => d.Route))

const JungsiCLazyRoute = JungsiCLazyImport.update({
  path: '/c',
  getParentRoute: () => JungsiRoute,
} as any).lazy(() => import('./routes/jungsi/c.lazy').then((d) => d.Route))

const JungsiBLazyRoute = JungsiBLazyImport.update({
  path: '/b',
  getParentRoute: () => JungsiRoute,
} as any).lazy(() => import('./routes/jungsi/b.lazy').then((d) => d.Route))

const JungsiALazyRoute = JungsiALazyImport.update({
  path: '/a',
  getParentRoute: () => JungsiRoute,
} as any).lazy(() => import('./routes/jungsi/a.lazy').then((d) => d.Route))

const ExploreEarlySubjectLazyRoute = ExploreEarlySubjectLazyImport.update({
  path: '/explore/early-subject',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/explore/early-subject.lazy').then((d) => d.Route),
)

const ExploreEarlyComprehensiveLazyRoute =
  ExploreEarlyComprehensiveLazyImport.update({
    path: '/explore/early-comprehensive',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/explore/early-comprehensive.lazy').then((d) => d.Route),
  )

const ExplainServiceLazyRoute = ExplainServiceLazyImport.update({
  path: '/explain/service',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/explain/service.lazy').then((d) => d.Route),
)

const ExplainRefundLazyRoute = ExplainRefundLazyImport.update({
  path: '/explain/refund',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/explain/refund.lazy').then((d) => d.Route),
)

const ExplainPrivacyLazyRoute = ExplainPrivacyLazyImport.update({
  path: '/explain/privacy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/explain/privacy.lazy').then((d) => d.Route),
)

const AnalysisPerformanceLazyRoute = AnalysisPerformanceLazyImport.update({
  path: '/analysis/performance',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/analysis/performance.lazy').then((d) => d.Route),
)

const AnalysisComparisonLazyRoute = AnalysisComparisonLazyImport.update({
  path: '/analysis/comparison',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/analysis/comparison.lazy').then((d) => d.Route),
)

const naverRedirectLazyRoute = naverRedirectLazyImport
  .update({
    path: '/redirect',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(naver)/redirect.lazy').then((d) => d.Route))

const UsersLayoutRoute = UsersLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => UsersRoute,
} as any)

const SusiLayoutRoute = SusiLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => SusiRoute,
} as any)

const OrderProductIdRoute = OrderProductIdImport.update({
  path: '/order/$productId',
  getParentRoute: () => rootRoute,
} as any)

const OfficerLayoutRoute = OfficerLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => OfficerRoute,
} as any)

const JungsiLayoutRoute = JungsiLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => JungsiRoute,
} as any)

const ExploreUniversityRoute = ExploreUniversityImport.update({
  path: '/explore/university',
  getParentRoute: () => rootRoute,
} as any)

const ExploreRecruitmentUnitRoute = ExploreRecruitmentUnitImport.update({
  path: '/explore/recruitment-unit',
  getParentRoute: () => rootRoute,
} as any)

const ExploreAdmissionRoute = ExploreAdmissionImport.update({
  path: '/explore/admission',
  getParentRoute: () => rootRoute,
} as any)

const EvaluationLayoutRoute = EvaluationLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => EvaluationRoute,
} as any)

const AuthResetPasswordRoute = AuthResetPasswordImport.update({
  path: '/auth/reset-password',
  getParentRoute: () => rootRoute,
} as any)

const AuthRegisterRoute = AuthRegisterImport.update({
  path: '/auth/register',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const OfficialNoticeIndexLazyRoute = OfficialNoticeIndexLazyImport.update({
  path: '/official/notice/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/official/notice.index.lazy').then((d) => d.Route),
)

const UsersLayoutSchoolRecordLazyRoute =
  UsersLayoutSchoolRecordLazyImport.update({
    path: '/school-record',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/school-record.lazy').then((d) => d.Route),
  )

const UsersLayoutProfileLazyRoute = UsersLayoutProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => UsersLayoutRoute,
} as any).lazy(() =>
  import('./routes/users/_layout/profile.lazy').then((d) => d.Route),
)

const UsersLayoutMockExamLazyRoute = UsersLayoutMockExamLazyImport.update({
  path: '/mock-exam',
  getParentRoute: () => UsersLayoutRoute,
} as any).lazy(() =>
  import('./routes/users/_layout/mock-exam.lazy').then((d) => d.Route),
)

const UsersLayoutAdditionalFileLazyRoute =
  UsersLayoutAdditionalFileLazyImport.update({
    path: '/additional-file',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/additional-file.lazy').then((d) => d.Route),
  )

const SusiLayoutInterestLazyRoute = SusiLayoutInterestLazyImport.update({
  path: '/interest',
  getParentRoute: () => SusiLayoutRoute,
} as any).lazy(() =>
  import('./routes/susi/_layout.interest.lazy').then((d) => d.Route),
)

const SusiLayoutCombinationLazyRoute = SusiLayoutCombinationLazyImport.update({
  path: '/combination',
  getParentRoute: () => SusiLayoutRoute,
} as any).lazy(() =>
  import('./routes/susi/_layout.combination.lazy').then((d) => d.Route),
)

const OfficialNoticePostIdLazyRoute = OfficialNoticePostIdLazyImport.update({
  path: '/official/notice/$postId',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/official/notice.$postId.lazy').then((d) => d.Route),
)

const OfficerLayoutProfileLazyRoute = OfficerLayoutProfileLazyImport.update({
  path: '/profile',
  getParentRoute: () => OfficerLayoutRoute,
} as any).lazy(() =>
  import('./routes/officer/_layout/profile.lazy').then((d) => d.Route),
)

const JungsiLayoutInterestLazyRoute = JungsiLayoutInterestLazyImport.update({
  path: '/interest',
  getParentRoute: () => JungsiLayoutRoute,
} as any).lazy(() =>
  import('./routes/jungsi/_layout.interest.lazy').then((d) => d.Route),
)

const JungsiLayoutCombinationLazyRoute =
  JungsiLayoutCombinationLazyImport.update({
    path: '/combination',
    getParentRoute: () => JungsiLayoutRoute,
  } as any).lazy(() =>
    import('./routes/jungsi/_layout.combination.lazy').then((d) => d.Route),
  )

const EvaluationLayoutRequestLazyRoute =
  EvaluationLayoutRequestLazyImport.update({
    path: '/request',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/request.lazy').then((d) => d.Route),
  )

const EvaluationLayoutListLazyRoute = EvaluationLayoutListLazyImport.update({
  path: '/list',
  getParentRoute: () => EvaluationLayoutRoute,
} as any).lazy(() =>
  import('./routes/evaluation/_layout/list.lazy').then((d) => d.Route),
)

const EvaluationLayoutCompatibilityLazyRoute =
  EvaluationLayoutCompatibilityLazyImport.update({
    path: '/compatibility',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/compatibility.lazy').then(
      (d) => d.Route,
    ),
  )

const UsersLayoutPaymentIndexLazyRoute =
  UsersLayoutPaymentIndexLazyImport.update({
    path: '/payment/',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/payment.index.lazy').then((d) => d.Route),
  )

const OfficerLayoutApplyIndexLazyRoute =
  OfficerLayoutApplyIndexLazyImport.update({
    path: '/apply/',
    getParentRoute: () => OfficerLayoutRoute,
  } as any).lazy(() =>
    import('./routes/officer/_layout/apply.index.lazy').then((d) => d.Route),
  )

const EvaluationLayoutSelfIndexLazyRoute =
  EvaluationLayoutSelfIndexLazyImport.update({
    path: '/self/',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/self.index.lazy').then((d) => d.Route),
  )

const UsersLayoutPaymentIdLazyRoute = UsersLayoutPaymentIdLazyImport.update({
  path: '/payment/$id',
  getParentRoute: () => UsersLayoutRoute,
} as any).lazy(() =>
  import('./routes/users/_layout/payment.$id.lazy').then((d) => d.Route),
)

const OfficerLayoutApplyStudentIdLazyRoute =
  OfficerLayoutApplyStudentIdLazyImport.update({
    path: '/apply/$studentId',
    getParentRoute: () => OfficerLayoutRoute,
  } as any).lazy(() =>
    import('./routes/officer/_layout/apply.$studentId.lazy').then(
      (d) => d.Route,
    ),
  )

const EvaluationLayoutSelfEditLazyRoute =
  EvaluationLayoutSelfEditLazyImport.update({
    path: '/self/edit',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/self.edit.lazy').then((d) => d.Route),
  )

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterImport
      parentRoute: typeof rootRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordImport
      parentRoute: typeof rootRoute
    }
    '/evaluation': {
      id: '/evaluation'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationImport
      parentRoute: typeof rootRoute
    }
    '/evaluation/_layout': {
      id: '/evaluation/_layout'
      path: '/evaluation'
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationLayoutImport
      parentRoute: typeof EvaluationRoute
    }
    '/explore/admission': {
      id: '/explore/admission'
      path: '/explore/admission'
      fullPath: '/explore/admission'
      preLoaderRoute: typeof ExploreAdmissionImport
      parentRoute: typeof rootRoute
    }
    '/explore/recruitment-unit': {
      id: '/explore/recruitment-unit'
      path: '/explore/recruitment-unit'
      fullPath: '/explore/recruitment-unit'
      preLoaderRoute: typeof ExploreRecruitmentUnitImport
      parentRoute: typeof rootRoute
    }
    '/explore/university': {
      id: '/explore/university'
      path: '/explore/university'
      fullPath: '/explore/university'
      preLoaderRoute: typeof ExploreUniversityImport
      parentRoute: typeof rootRoute
    }
    '/jungsi': {
      id: '/jungsi'
      path: '/jungsi'
      fullPath: '/jungsi'
      preLoaderRoute: typeof JungsiImport
      parentRoute: typeof rootRoute
    }
    '/jungsi/_layout': {
      id: '/jungsi/_layout'
      path: '/jungsi'
      fullPath: '/jungsi'
      preLoaderRoute: typeof JungsiLayoutImport
      parentRoute: typeof JungsiRoute
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerImport
      parentRoute: typeof rootRoute
    }
    '/officer/_layout': {
      id: '/officer/_layout'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerLayoutImport
      parentRoute: typeof OfficerRoute
    }
    '/order/$productId': {
      id: '/order/$productId'
      path: '/order/$productId'
      fullPath: '/order/$productId'
      preLoaderRoute: typeof OrderProductIdImport
      parentRoute: typeof rootRoute
    }
    '/susi': {
      id: '/susi'
      path: '/susi'
      fullPath: '/susi'
      preLoaderRoute: typeof SusiImport
      parentRoute: typeof rootRoute
    }
    '/susi/_layout': {
      id: '/susi/_layout'
      path: '/susi'
      fullPath: '/susi'
      preLoaderRoute: typeof SusiLayoutImport
      parentRoute: typeof SusiRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/users/_layout': {
      id: '/users/_layout'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersLayoutImport
      parentRoute: typeof UsersRoute
    }
    '/(naver)/redirect': {
      id: '/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof naverRedirectLazyImport
      parentRoute: typeof rootRoute
    }
    '/analysis/comparison': {
      id: '/analysis/comparison'
      path: '/analysis/comparison'
      fullPath: '/analysis/comparison'
      preLoaderRoute: typeof AnalysisComparisonLazyImport
      parentRoute: typeof rootRoute
    }
    '/analysis/performance': {
      id: '/analysis/performance'
      path: '/analysis/performance'
      fullPath: '/analysis/performance'
      preLoaderRoute: typeof AnalysisPerformanceLazyImport
      parentRoute: typeof rootRoute
    }
    '/explain/privacy': {
      id: '/explain/privacy'
      path: '/explain/privacy'
      fullPath: '/explain/privacy'
      preLoaderRoute: typeof ExplainPrivacyLazyImport
      parentRoute: typeof rootRoute
    }
    '/explain/refund': {
      id: '/explain/refund'
      path: '/explain/refund'
      fullPath: '/explain/refund'
      preLoaderRoute: typeof ExplainRefundLazyImport
      parentRoute: typeof rootRoute
    }
    '/explain/service': {
      id: '/explain/service'
      path: '/explain/service'
      fullPath: '/explain/service'
      preLoaderRoute: typeof ExplainServiceLazyImport
      parentRoute: typeof rootRoute
    }
    '/explore/early-comprehensive': {
      id: '/explore/early-comprehensive'
      path: '/explore/early-comprehensive'
      fullPath: '/explore/early-comprehensive'
      preLoaderRoute: typeof ExploreEarlyComprehensiveLazyImport
      parentRoute: typeof rootRoute
    }
    '/explore/early-subject': {
      id: '/explore/early-subject'
      path: '/explore/early-subject'
      fullPath: '/explore/early-subject'
      preLoaderRoute: typeof ExploreEarlySubjectLazyImport
      parentRoute: typeof rootRoute
    }
    '/jungsi/a': {
      id: '/jungsi/a'
      path: '/a'
      fullPath: '/jungsi/a'
      preLoaderRoute: typeof JungsiALazyImport
      parentRoute: typeof JungsiImport
    }
    '/jungsi/b': {
      id: '/jungsi/b'
      path: '/b'
      fullPath: '/jungsi/b'
      preLoaderRoute: typeof JungsiBLazyImport
      parentRoute: typeof JungsiImport
    }
    '/jungsi/c': {
      id: '/jungsi/c'
      path: '/c'
      fullPath: '/jungsi/c'
      preLoaderRoute: typeof JungsiCLazyImport
      parentRoute: typeof JungsiImport
    }
    '/official/faq': {
      id: '/official/faq'
      path: '/official/faq'
      fullPath: '/official/faq'
      preLoaderRoute: typeof OfficialFaqLazyImport
      parentRoute: typeof rootRoute
    }
    '/official/guide': {
      id: '/official/guide'
      path: '/official/guide'
      fullPath: '/official/guide'
      preLoaderRoute: typeof OfficialGuideLazyImport
      parentRoute: typeof rootRoute
    }
    '/susi/comprehensive': {
      id: '/susi/comprehensive'
      path: '/comprehensive'
      fullPath: '/susi/comprehensive'
      preLoaderRoute: typeof SusiComprehensiveLazyImport
      parentRoute: typeof SusiImport
    }
    '/susi/nonsul': {
      id: '/susi/nonsul'
      path: '/nonsul'
      fullPath: '/susi/nonsul'
      preLoaderRoute: typeof SusiNonsulLazyImport
      parentRoute: typeof SusiImport
    }
    '/susi/subject': {
      id: '/susi/subject'
      path: '/subject'
      fullPath: '/susi/subject'
      preLoaderRoute: typeof SusiSubjectLazyImport
      parentRoute: typeof SusiImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexImport
      parentRoute: typeof rootRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/evaluation/': {
      id: '/evaluation/'
      path: '/'
      fullPath: '/evaluation/'
      preLoaderRoute: typeof EvaluationIndexLazyImport
      parentRoute: typeof EvaluationImport
    }
    '/jungsi/': {
      id: '/jungsi/'
      path: '/'
      fullPath: '/jungsi/'
      preLoaderRoute: typeof JungsiIndexLazyImport
      parentRoute: typeof JungsiImport
    }
    '/susi/': {
      id: '/susi/'
      path: '/'
      fullPath: '/susi/'
      preLoaderRoute: typeof SusiIndexLazyImport
      parentRoute: typeof SusiImport
    }
    '/evaluation/_layout/compatibility': {
      id: '/evaluation/_layout/compatibility'
      path: '/compatibility'
      fullPath: '/evaluation/compatibility'
      preLoaderRoute: typeof EvaluationLayoutCompatibilityLazyImport
      parentRoute: typeof EvaluationLayoutImport
    }
    '/evaluation/_layout/list': {
      id: '/evaluation/_layout/list'
      path: '/list'
      fullPath: '/evaluation/list'
      preLoaderRoute: typeof EvaluationLayoutListLazyImport
      parentRoute: typeof EvaluationLayoutImport
    }
    '/evaluation/_layout/request': {
      id: '/evaluation/_layout/request'
      path: '/request'
      fullPath: '/evaluation/request'
      preLoaderRoute: typeof EvaluationLayoutRequestLazyImport
      parentRoute: typeof EvaluationLayoutImport
    }
    '/jungsi/_layout/combination': {
      id: '/jungsi/_layout/combination'
      path: '/combination'
      fullPath: '/jungsi/combination'
      preLoaderRoute: typeof JungsiLayoutCombinationLazyImport
      parentRoute: typeof JungsiLayoutImport
    }
    '/jungsi/_layout/interest': {
      id: '/jungsi/_layout/interest'
      path: '/interest'
      fullPath: '/jungsi/interest'
      preLoaderRoute: typeof JungsiLayoutInterestLazyImport
      parentRoute: typeof JungsiLayoutImport
    }
    '/officer/_layout/profile': {
      id: '/officer/_layout/profile'
      path: '/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof OfficerLayoutProfileLazyImport
      parentRoute: typeof OfficerLayoutImport
    }
    '/official/notice/$postId': {
      id: '/official/notice/$postId'
      path: '/official/notice/$postId'
      fullPath: '/official/notice/$postId'
      preLoaderRoute: typeof OfficialNoticePostIdLazyImport
      parentRoute: typeof rootRoute
    }
    '/susi/_layout/combination': {
      id: '/susi/_layout/combination'
      path: '/combination'
      fullPath: '/susi/combination'
      preLoaderRoute: typeof SusiLayoutCombinationLazyImport
      parentRoute: typeof SusiLayoutImport
    }
    '/susi/_layout/interest': {
      id: '/susi/_layout/interest'
      path: '/interest'
      fullPath: '/susi/interest'
      preLoaderRoute: typeof SusiLayoutInterestLazyImport
      parentRoute: typeof SusiLayoutImport
    }
    '/users/_layout/additional-file': {
      id: '/users/_layout/additional-file'
      path: '/additional-file'
      fullPath: '/users/additional-file'
      preLoaderRoute: typeof UsersLayoutAdditionalFileLazyImport
      parentRoute: typeof UsersLayoutImport
    }
    '/users/_layout/mock-exam': {
      id: '/users/_layout/mock-exam'
      path: '/mock-exam'
      fullPath: '/users/mock-exam'
      preLoaderRoute: typeof UsersLayoutMockExamLazyImport
      parentRoute: typeof UsersLayoutImport
    }
    '/users/_layout/profile': {
      id: '/users/_layout/profile'
      path: '/profile'
      fullPath: '/users/profile'
      preLoaderRoute: typeof UsersLayoutProfileLazyImport
      parentRoute: typeof UsersLayoutImport
    }
    '/users/_layout/school-record': {
      id: '/users/_layout/school-record'
      path: '/school-record'
      fullPath: '/users/school-record'
      preLoaderRoute: typeof UsersLayoutSchoolRecordLazyImport
      parentRoute: typeof UsersLayoutImport
    }
    '/official/notice/': {
      id: '/official/notice/'
      path: '/official/notice'
      fullPath: '/official/notice'
      preLoaderRoute: typeof OfficialNoticeIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/evaluation/_layout/self/edit': {
      id: '/evaluation/_layout/self/edit'
      path: '/self/edit'
      fullPath: '/evaluation/self/edit'
      preLoaderRoute: typeof EvaluationLayoutSelfEditLazyImport
      parentRoute: typeof EvaluationLayoutImport
    }
    '/officer/_layout/apply/$studentId': {
      id: '/officer/_layout/apply/$studentId'
      path: '/apply/$studentId'
      fullPath: '/officer/apply/$studentId'
      preLoaderRoute: typeof OfficerLayoutApplyStudentIdLazyImport
      parentRoute: typeof OfficerLayoutImport
    }
    '/users/_layout/payment/$id': {
      id: '/users/_layout/payment/$id'
      path: '/payment/$id'
      fullPath: '/users/payment/$id'
      preLoaderRoute: typeof UsersLayoutPaymentIdLazyImport
      parentRoute: typeof UsersLayoutImport
    }
    '/evaluation/_layout/self/': {
      id: '/evaluation/_layout/self/'
      path: '/self'
      fullPath: '/evaluation/self'
      preLoaderRoute: typeof EvaluationLayoutSelfIndexLazyImport
      parentRoute: typeof EvaluationLayoutImport
    }
    '/officer/_layout/apply/': {
      id: '/officer/_layout/apply/'
      path: '/apply'
      fullPath: '/officer/apply'
      preLoaderRoute: typeof OfficerLayoutApplyIndexLazyImport
      parentRoute: typeof OfficerLayoutImport
    }
    '/users/_layout/payment/': {
      id: '/users/_layout/payment/'
      path: '/payment'
      fullPath: '/users/payment'
      preLoaderRoute: typeof UsersLayoutPaymentIndexLazyImport
      parentRoute: typeof UsersLayoutImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthLoginRoute,
  AuthRegisterRoute,
  AuthResetPasswordRoute,
  EvaluationRoute: EvaluationRoute.addChildren({
    EvaluationLayoutRoute: EvaluationLayoutRoute.addChildren({
      EvaluationLayoutCompatibilityLazyRoute,
      EvaluationLayoutListLazyRoute,
      EvaluationLayoutRequestLazyRoute,
      EvaluationLayoutSelfEditLazyRoute,
      EvaluationLayoutSelfIndexLazyRoute,
    }),
    EvaluationIndexLazyRoute,
  }),
  ExploreAdmissionRoute,
  ExploreRecruitmentUnitRoute,
  ExploreUniversityRoute,
  JungsiRoute: JungsiRoute.addChildren({
    JungsiLayoutRoute: JungsiLayoutRoute.addChildren({
      JungsiLayoutCombinationLazyRoute,
      JungsiLayoutInterestLazyRoute,
    }),
    JungsiALazyRoute,
    JungsiBLazyRoute,
    JungsiCLazyRoute,
    JungsiIndexLazyRoute,
  }),
  OfficerRoute: OfficerRoute.addChildren({
    OfficerLayoutRoute: OfficerLayoutRoute.addChildren({
      OfficerLayoutProfileLazyRoute,
      OfficerLayoutApplyStudentIdLazyRoute,
      OfficerLayoutApplyIndexLazyRoute,
    }),
  }),
  OrderProductIdRoute,
  SusiRoute: SusiRoute.addChildren({
    SusiLayoutRoute: SusiLayoutRoute.addChildren({
      SusiLayoutCombinationLazyRoute,
      SusiLayoutInterestLazyRoute,
    }),
    SusiComprehensiveLazyRoute,
    SusiNonsulLazyRoute,
    SusiSubjectLazyRoute,
    SusiIndexLazyRoute,
  }),
  UsersRoute: UsersRoute.addChildren({
    UsersLayoutRoute: UsersLayoutRoute.addChildren({
      UsersLayoutAdditionalFileLazyRoute,
      UsersLayoutMockExamLazyRoute,
      UsersLayoutProfileLazyRoute,
      UsersLayoutSchoolRecordLazyRoute,
      UsersLayoutPaymentIdLazyRoute,
      UsersLayoutPaymentIndexLazyRoute,
    }),
  }),
  naverRedirectLazyRoute,
  AnalysisComparisonLazyRoute,
  AnalysisPerformanceLazyRoute,
  ExplainPrivacyLazyRoute,
  ExplainRefundLazyRoute,
  ExplainServiceLazyRoute,
  ExploreEarlyComprehensiveLazyRoute,
  ExploreEarlySubjectLazyRoute,
  OfficialFaqLazyRoute,
  OfficialGuideLazyRoute,
  ProductsIndexRoute,
  AnalysisIndexLazyRoute,
  OfficialNoticePostIdLazyRoute,
  OfficialNoticeIndexLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/register",
        "/auth/reset-password",
        "/evaluation",
        "/explore/admission",
        "/explore/recruitment-unit",
        "/explore/university",
        "/jungsi",
        "/officer",
        "/order/$productId",
        "/susi",
        "/users",
        "/redirect",
        "/analysis/comparison",
        "/analysis/performance",
        "/explain/privacy",
        "/explain/refund",
        "/explain/service",
        "/explore/early-comprehensive",
        "/explore/early-subject",
        "/official/faq",
        "/official/guide",
        "/products/",
        "/analysis/",
        "/official/notice/$postId",
        "/official/notice/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/register": {
      "filePath": "auth/register.tsx"
    },
    "/auth/reset-password": {
      "filePath": "auth/reset-password.tsx"
    },
    "/evaluation": {
      "filePath": "evaluation",
      "children": [
        "/evaluation/_layout",
        "/evaluation/"
      ]
    },
    "/evaluation/_layout": {
      "filePath": "evaluation/_layout.tsx",
      "parent": "/evaluation",
      "children": [
        "/evaluation/_layout/compatibility",
        "/evaluation/_layout/list",
        "/evaluation/_layout/request",
        "/evaluation/_layout/self/edit",
        "/evaluation/_layout/self/"
      ]
    },
    "/explore/admission": {
      "filePath": "explore/admission.tsx"
    },
    "/explore/recruitment-unit": {
      "filePath": "explore/recruitment-unit.tsx"
    },
    "/explore/university": {
      "filePath": "explore/university.tsx"
    },
    "/jungsi": {
      "filePath": "jungsi",
      "children": [
        "/jungsi/_layout",
        "/jungsi/a",
        "/jungsi/b",
        "/jungsi/c",
        "/jungsi/"
      ]
    },
    "/jungsi/_layout": {
      "filePath": "jungsi/_layout.tsx",
      "parent": "/jungsi",
      "children": [
        "/jungsi/_layout/combination",
        "/jungsi/_layout/interest"
      ]
    },
    "/officer": {
      "filePath": "officer",
      "children": [
        "/officer/_layout"
      ]
    },
    "/officer/_layout": {
      "filePath": "officer/_layout.tsx",
      "parent": "/officer",
      "children": [
        "/officer/_layout/profile",
        "/officer/_layout/apply/$studentId",
        "/officer/_layout/apply/"
      ]
    },
    "/order/$productId": {
      "filePath": "order/$productId.tsx"
    },
    "/susi": {
      "filePath": "susi",
      "children": [
        "/susi/_layout",
        "/susi/comprehensive",
        "/susi/nonsul",
        "/susi/subject",
        "/susi/"
      ]
    },
    "/susi/_layout": {
      "filePath": "susi/_layout.tsx",
      "parent": "/susi",
      "children": [
        "/susi/_layout/combination",
        "/susi/_layout/interest"
      ]
    },
    "/users": {
      "filePath": "users",
      "children": [
        "/users/_layout"
      ]
    },
    "/users/_layout": {
      "filePath": "users/_layout.tsx",
      "parent": "/users",
      "children": [
        "/users/_layout/additional-file",
        "/users/_layout/mock-exam",
        "/users/_layout/profile",
        "/users/_layout/school-record",
        "/users/_layout/payment/$id",
        "/users/_layout/payment/"
      ]
    },
    "/redirect": {
      "filePath": "(naver)/redirect.lazy.tsx"
    },
    "/analysis/comparison": {
      "filePath": "analysis/comparison.lazy.tsx"
    },
    "/analysis/performance": {
      "filePath": "analysis/performance.lazy.tsx"
    },
    "/explain/privacy": {
      "filePath": "explain/privacy.lazy.tsx"
    },
    "/explain/refund": {
      "filePath": "explain/refund.lazy.tsx"
    },
    "/explain/service": {
      "filePath": "explain/service.lazy.tsx"
    },
    "/explore/early-comprehensive": {
      "filePath": "explore/early-comprehensive.lazy.tsx"
    },
    "/explore/early-subject": {
      "filePath": "explore/early-subject.lazy.tsx"
    },
    "/jungsi/a": {
      "filePath": "jungsi/a.lazy.tsx",
      "parent": "/jungsi"
    },
    "/jungsi/b": {
      "filePath": "jungsi/b.lazy.tsx",
      "parent": "/jungsi"
    },
    "/jungsi/c": {
      "filePath": "jungsi/c.lazy.tsx",
      "parent": "/jungsi"
    },
    "/official/faq": {
      "filePath": "official/faq.lazy.tsx"
    },
    "/official/guide": {
      "filePath": "official/guide.lazy.tsx"
    },
    "/susi/comprehensive": {
      "filePath": "susi/comprehensive.lazy.tsx",
      "parent": "/susi"
    },
    "/susi/nonsul": {
      "filePath": "susi/nonsul.lazy.tsx",
      "parent": "/susi"
    },
    "/susi/subject": {
      "filePath": "susi/subject.lazy.tsx",
      "parent": "/susi"
    },
    "/products/": {
      "filePath": "products/index.tsx"
    },
    "/analysis/": {
      "filePath": "analysis/index.lazy.tsx"
    },
    "/evaluation/": {
      "filePath": "evaluation/index.lazy.tsx",
      "parent": "/evaluation"
    },
    "/jungsi/": {
      "filePath": "jungsi/index.lazy.tsx",
      "parent": "/jungsi"
    },
    "/susi/": {
      "filePath": "susi/index.lazy.tsx",
      "parent": "/susi"
    },
    "/evaluation/_layout/compatibility": {
      "filePath": "evaluation/_layout/compatibility.lazy.tsx",
      "parent": "/evaluation/_layout"
    },
    "/evaluation/_layout/list": {
      "filePath": "evaluation/_layout/list.lazy.tsx",
      "parent": "/evaluation/_layout"
    },
    "/evaluation/_layout/request": {
      "filePath": "evaluation/_layout/request.lazy.tsx",
      "parent": "/evaluation/_layout"
    },
    "/jungsi/_layout/combination": {
      "filePath": "jungsi/_layout.combination.lazy.tsx",
      "parent": "/jungsi/_layout"
    },
    "/jungsi/_layout/interest": {
      "filePath": "jungsi/_layout.interest.lazy.tsx",
      "parent": "/jungsi/_layout"
    },
    "/officer/_layout/profile": {
      "filePath": "officer/_layout/profile.lazy.tsx",
      "parent": "/officer/_layout"
    },
    "/official/notice/$postId": {
      "filePath": "official/notice.$postId.lazy.tsx"
    },
    "/susi/_layout/combination": {
      "filePath": "susi/_layout.combination.lazy.tsx",
      "parent": "/susi/_layout"
    },
    "/susi/_layout/interest": {
      "filePath": "susi/_layout.interest.lazy.tsx",
      "parent": "/susi/_layout"
    },
    "/users/_layout/additional-file": {
      "filePath": "users/_layout/additional-file.lazy.tsx",
      "parent": "/users/_layout"
    },
    "/users/_layout/mock-exam": {
      "filePath": "users/_layout/mock-exam.lazy.tsx",
      "parent": "/users/_layout"
    },
    "/users/_layout/profile": {
      "filePath": "users/_layout/profile.lazy.tsx",
      "parent": "/users/_layout"
    },
    "/users/_layout/school-record": {
      "filePath": "users/_layout/school-record.lazy.tsx",
      "parent": "/users/_layout"
    },
    "/official/notice/": {
      "filePath": "official/notice.index.lazy.tsx"
    },
    "/evaluation/_layout/self/edit": {
      "filePath": "evaluation/_layout/self.edit.lazy.tsx",
      "parent": "/evaluation/_layout"
    },
    "/officer/_layout/apply/$studentId": {
      "filePath": "officer/_layout/apply.$studentId.lazy.tsx",
      "parent": "/officer/_layout"
    },
    "/users/_layout/payment/$id": {
      "filePath": "users/_layout/payment.$id.lazy.tsx",
      "parent": "/users/_layout"
    },
    "/evaluation/_layout/self/": {
      "filePath": "evaluation/_layout/self.index.lazy.tsx",
      "parent": "/evaluation/_layout"
    },
    "/officer/_layout/apply/": {
      "filePath": "officer/_layout/apply.index.lazy.tsx",
      "parent": "/officer/_layout"
    },
    "/users/_layout/payment/": {
      "filePath": "users/_layout/payment.index.lazy.tsx",
      "parent": "/users/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
