export interface SuSiSubject {
  id: number; // id
  unified_id: string; // 통합 아이디 (ex. U0094121)
  year: number | null; // 년도
  region: string | null; // 지역구분
  university_name: string | null; // 대학명
  university_code: string | null; // 대학코드
  national_or_private: string | null; // '국립/사립'
  basic_type: string | null; // 기본유형
  detailed_type: string | null; // 전형세부유형
  type_name: string | null; // 전형명
  central_classification: string | null; // 중심전형분류
  department: string | null; // 계열
  college: string | null; // 단과대학
  recruitment_unit_name: string | null; // 모집단위명
  large_department: string | null; // 대계열
  medium_department: string | null; // 중계열
  small_department: string | null; // 소계열
  recruitment_number: string | null; // 모집인원
  selection_model: string | null; // 선발모형
  selection_ratio: string | null; // 선발비율
  selection_method: string | null; // 전형방법
  curriculum: number | null; // 교과
  interview: number | null; // 면접
  attendance: number | null; // 출결
  volunteer: number | null; // 봉사
  document_non_academic: number | null; // '서류(비교과)'
  step1_score: number | null; // '(2단계)1단계성적'
  step2_others: number | null; // '(2단계)그외'
  practical_skills: number | null; // 실무
  step2_other_details: string | null; // '(2단계)그외내역'
  step2_interview: string | null; // (2단계) 면접
  application_eligibility_text: string | null; // 지원자격TEXT
  student_record_utilization_index: string | null; // 학생부활용지표
  curriculum_reflection_semester: number | null; // 교과_반영학기
  first_year_ratio: number | null; // '1학년비율'
  second_year_ratio: number | null; // '2학년비율'
  third_year_ratio: number | null; // '3학년비율'
  second_third_year_ratio: number | null; // '2-3학년비율'
  first_second_third_year_ratio: number | null; // '1-2-3학년비율'
  curriculum_grade_1: number | null; // 교과_등급점수_1등급
  curriculum_grade_2: number | null; // 교과_등급점수_2등급
  curriculum_grade_3: number | null; // 교과_등급점수_3등급
  curriculum_grade_4: number | null; // 교과_등급점수_4등급
  curriculum_grade_5: number | null; // 교과_등급점수_5등급
  curriculum_grade_6: number | null; // 교과_등급점수_6등급
  curriculum_grade_7: number | null; // 교과_등급점수_7등급
  curriculum_grade_8: number | null; // 교과_등급점수_8등급
  curriculum_grade_9: number | null; // 교과_등급점수_9등급
  common_general_and_career_integration: number | null; // 공통일반과진로가통합
  common_general_subject_ratio: number | null; // 공통일반과목비율
  reflected_subject_1_year_korean: number | null; // '1년_국어'
  reflected_subject_1_year_math: number | null; // '1년_수학'
  reflected_subject_1_year_english: number | null; // '1년_영어'
  reflected_subject_1_year_science: number | null; // '1년_과학'
  reflected_subject_1_year_social: number | null; // '1년_사회'
  reflected_subject_1_year_korean_history: number | null; // '1년_한국사'
  reflected_subject_1_year_other: number | null; // '1년_기가외'
  number_of_optional_subjects_1: number | null; // '1년_선택과목수'
  total_number_of_top_subjects_1: number | null; // '1_년전체상위과목수'
  number_of_top_subjects_per_subject_1: number | null; // '1_년과목별상위과목수'
  reflected_subject_2_3_years_korean: number | null; // '2-3년_국어'
  reflected_subject_2_3_years_math: number | null; // '2-3년_수학'
  reflected_subject_2_3_years_english: number | null; // '2-3년_영어'
  reflected_subject_2_3_years_science: number | null; // '2-3년_과학'
  reflected_subject_2_3_years_social: number | null; // '2-3년_사회'
  reflected_subject_2_3_years_korean_history: number | null; // '2-3년_한국사'
  reflected_subject_2_3_years_other: number | null; // '2-3년_기가외'
  number_of_optional_subjects_2_3: number | null; // '2-3년_선택과목수'
  total_number_of_top_subjects_2_3: number | null; // '2-3년_전체상위과목수'
  number_of_top_subjects_per_subject_2_3: number | null; // '2-3년_과목별상위과목수'
  common_general_reflection_method: string | null; // 공통일반반영방식
  perfect_score: number | null; // 만점
  attendance_usage: number | null; // 출결사용여부
  attendance_usage_ratio: number | null; // 출결사용비중
  absence_1: number | null; // 결석1회
  absence_2: number | null; // 결석2회
  absence_3: number | null; // 결석3회
  absence_4: number | null; // 결석4회
  absence_5: number | null; // 결석5회
  absence_6: number | null; // 결석6회
  absence_7: number | null; // 결석7회
  absence_8: number | null; // 결석8회
  absence_9: number | null; // 결석9회
  absence_10: number | null; // 결석10회
  absence_11: number | null; // 결석11회
  absence_12: number | null; // 결석12회
  absence_13: number | null; // 결석13회
  absence_14: number | null; // 결석14회
  absence_15: number | null; // 결석15회
  absence_16: number | null; // 결석16회
  absence_17: number | null; // 결석17회
  absence_18: number | null; // 결석18회
  absence_19: number | null; // 결석19회
  absence_20: number | null; // 결석20회
  career_subject_application: number | null; // 진로과목적용여부
  career_subject_reflection_method: string | null; // 진로과목반영방식
  career_optional_subject: number | null; // 진로선택과목
  career_if_2: string | null; // 진로2일경우
  career_optional_subject_A: number | null; // 진로선택과목A
  career_optional_subject_B: number | null; // 진로선택과목B
  career_optional_subject_C: number | null; // 진로선택과목C
  A_distribution_ratio: number | null; // A분포비율
  B_distribution_ratio: number | null; // B분포비율
  C_distribution_ratio: number | null; // C분포비율
  career_subject_ratio: number | null; // 진로과목비율
  career_subject_additional_points: number | null; // 진로과목가산
  number_of_top_subjects_in_all_career_subjects: number | null; // 진로전체과목중상위과목수
  number_of_top_subjects_in_career_curriculum: number | null; // 진로교과중상위과목수
  grade_cut: number | null; // 등급컷
  grade_cut_70: number | null; // 등급컷 70
  converted_score_cut: number | null; // 환산점수컷
  converted_score_total: number | null; // 환산점수총점
  risk_level_plus5: number | null; // '환산점수위험도(+)5'
  risk_level_plus4: number | null; // '위험도(+)4'
  risk_level_plus3: number | null; // '위험도(+)3'
  risk_level_plus2: number | null; // '위험도(+)2'
  risk_level_plus1: number | null; // '위험도(+)1'
  risk_level_minus1: number | null; // '위험도(-1)'
  risk_level_minus2: number | null; // '위험도(-2)'
  risk_level_minus3: number | null; // '위험도(-3)'
  risk_level_minus4: number | null; // '위험도(-4)'
  risk_level_minus5: number | null; // '위험도(-5)'
  minimum_academic_standards_applied: number | null; // 최저학력기준_반영여부
  minimum_academic_standards_text: string | null; // 수능최저학력기준TEXT
  minimum_korean: number | null; // 최저국어
  minimum_math: number | null; // 최저수학
  minimum_math_science_engineering: number | null; // '최저수학(미/기)'
  english: number | null; // 영어
  social_studies: number | null; // 사탐
  science_studies: number | null; // 과탐
  calculation_studies: number | null; // 탐계산
  minimum_count: number | null; // 최저갯수
  minimum_sum: number | null; // '최저합'
  korean_history: number | null; // '한국사'
  others: number | null; // 그외
  others_details: string | null; // 그외상세
  additional_points: number | null; // 가산점
  additional_points_text: string | null; // 가산점TEXT
  interview_score_applied: string | null; // 면접점수반영여부
  interview_type: string | null; // 면접유형
  interview_resources: string | null; // 면접시활용자료
  interview_method: string | null; // 면접진행방식
  interview_evaluation_content: string | null; // 면접평가내용
  interview_date_text: string | null; // 면접날짜TEXT
  interview_time: string | null; // 면접시간
  curriculum_calculation_formula: number | null; // 교과계산식
  admission_criteria_2024: string | null; // '2024년입결기준'
  admission_2024_grade: string | null; // '2024학년도입결(등급)'
  admission_2024_converted_score: string | null; // '2024학년도입결(환산점수)'
  competition_rate_2024: string | null; // '2024학년도경쟁률'
  replenishment_2024: string | null; // '2024충원'
  admission_criteria_2023: string | null; // '2023학년도기준'
  admission_2023_grade: string | null; // '2023학년도입결(등급)'
  admission_2023_converted_score: string | null; // '2023학년도입결(환산점수)'
  competition_rate_2023: string | null; // '2023학년도경쟁률'
  replenishment_2023: string | null; // '2023충원'
  admission_criteria_2022: string | null; // '2022학년도기준'
  admission_2022_grade: string | null; // '2022학년도입결'
  competition_rate_2022: string | null; // '2022학년도경쟁률'
  replenishment_2022: string | null; // '2022충원'
  admission_2021_grade: string | null; // '2021학년도입결'
  competition_rate_2021: string | null; // '2021학년도경쟁률'
  replenishment_2021: string | null; // '2021충원'
  admission_2020_grade: string | null; // '2020학년도입결'
  competition_rate_2020: string | null; // '2020학년도경쟁률'
  replenishment_2020: string | null; // '2020충원'
  application_notes: string | null; // 지원시유의사항
}
