/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as H4RouteImport } from './routes/h4'
import { Route as H3RouteImport } from './routes/h3'
import { Route as H2RouteImport } from './routes/h2'
import { Route as H1RouteImport } from './routes/h1'
import { Route as TryRouteRouteImport } from './routes/try/route'
import { Route as ScoreAnalysisRouteRouteImport } from './routes/score-analysis/route'
import { Route as MsRouteRouteImport } from './routes/ms/route'
import { Route as MockAnalysisRouteRouteImport } from './routes/mock-analysis/route'
import { Route as GradeAnalysisRouteRouteImport } from './routes/grade-analysis/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as UsersLayoutRouteImport } from './routes/users/_layout'
import { Route as TestLoginDebugRouteImport } from './routes/test/login-debug'
import { Route as TestAuthMeRouteImport } from './routes/test/auth-me'
import { Route as OrderProductIdRouteImport } from './routes/order/$productId'
import { Route as OfficerLayoutRouteImport } from './routes/officer/_layout'
import { Route as MsLayoutRouteImport } from './routes/ms/_layout'
import { Route as MockAnalysisLayoutRouteImport } from './routes/mock-analysis/_layout'
import { Route as GradeAnalysisLayoutRouteImport } from './routes/grade-analysis/_layout'
import { Route as ExploreUniversityRouteImport } from './routes/explore/university'
import { Route as ExploreRecruitmentUnitRouteImport } from './routes/explore/recruitment-unit'
import { Route as ExploreAdmissionRouteImport } from './routes/explore/admission'
import { Route as EvaluationLayoutRouteImport } from './routes/evaluation/_layout'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthOauthCallbackRouteImport } from './routes/auth/oauth/callback'

const TryIndexLazyRouteImport = createFileRoute('/try/')()
const ScoreAnalysisIndexLazyRouteImport = createFileRoute('/score-analysis/')()
const MsIndexLazyRouteImport = createFileRoute('/ms/')()
const GradeAnalysisIndexLazyRouteImport = createFileRoute('/grade-analysis/')()
const EvaluationIndexLazyRouteImport = createFileRoute('/evaluation/')()
const AnalysisIndexLazyRouteImport = createFileRoute('/analysis/')()
const OfficialGuideLazyRouteImport = createFileRoute('/official/guide')()
const OfficialFaqLazyRouteImport = createFileRoute('/official/faq')()
const ExploreSusiKyokwaLazyRouteImport = createFileRoute(
  '/explore/susi-kyokwa',
)()
const ExploreSusiJonghapLazyRouteImport = createFileRoute(
  '/explore/susi-jonghap',
)()
const ExplainServiceLazyRouteImport = createFileRoute('/explain/service')()
const ExplainRefundLazyRouteImport = createFileRoute('/explain/refund')()
const ExplainPrivacyLazyRouteImport = createFileRoute('/explain/privacy')()
const AnalysisPerformanceLazyRouteImport = createFileRoute(
  '/analysis/performance',
)()
const naverRedirectLazyRouteImport = createFileRoute('/(naver)/redirect')()
const OfficialNoticeIndexLazyRouteImport =
  createFileRoute('/official/notice/')()
const UsersLayoutSchoolRecordLazyRouteImport = createFileRoute(
  '/users/_layout/school-record',
)()
const UsersLayoutProfileLazyRouteImport = createFileRoute(
  '/users/_layout/profile',
)()
const UsersLayoutMockExamLazyRouteImport = createFileRoute(
  '/users/_layout/mock-exam',
)()
const UsersLayoutAdditionalFileLazyRouteImport = createFileRoute(
  '/users/_layout/additional-file',
)()
const OfficialNoticePostIdLazyRouteImport = createFileRoute(
  '/official/notice/$postId',
)()
const OfficerLayoutProfileLazyRouteImport = createFileRoute(
  '/officer/_layout/profile',
)()
const MsLayoutSubjectLazyRouteImport = createFileRoute('/ms/_layout/subject')()
const MsLayoutSetukLazyRouteImport = createFileRoute('/ms/_layout/setuk')()
const MsLayoutSchoolRecordLazyRouteImport = createFileRoute(
  '/ms/_layout/school-record',
)()
const MsLayoutRequestLazyRouteImport = createFileRoute('/ms/_layout/request')()
const MsLayoutPerformanceLazyRouteImport = createFileRoute(
  '/ms/_layout/performance',
)()
const MsLayoutNonsulLazyRouteImport = createFileRoute('/ms/_layout/nonsul')()
const MsLayoutKyokwaLazyRouteImport = createFileRoute('/ms/_layout/kyokwa')()
const MsLayoutJonghapLazyRouteImport = createFileRoute('/ms/_layout/jonghap')()
const MsLayoutInterestLazyRouteImport = createFileRoute(
  '/ms/_layout/interest',
)()
const MsLayoutEvaluationListLazyRouteImport = createFileRoute(
  '/ms/_layout/evaluation-list',
)()
const MsLayoutCreativeActivityLazyRouteImport = createFileRoute(
  '/ms/_layout/creative-activity',
)()
const MsLayoutComprehensiveLazyRouteImport = createFileRoute(
  '/ms/_layout/comprehensive',
)()
const MsLayoutCompatibilityLazyRouteImport = createFileRoute(
  '/ms/_layout/compatibility',
)()
const MsLayoutCombinationLazyRouteImport = createFileRoute(
  '/ms/_layout/combination',
)()
const MockAnalysisLayoutWrongAnswersLazyRouteImport = createFileRoute(
  '/mock-analysis/_layout/wrong-answers',
)()
const MockAnalysisLayoutTargetUniversityLazyRouteImport = createFileRoute(
  '/mock-analysis/_layout/target-university',
)()
const MockAnalysisLayoutStatisticsLazyRouteImport = createFileRoute(
  '/mock-analysis/_layout/statistics',
)()
const MockAnalysisLayoutScoreInputLazyRouteImport = createFileRoute(
  '/mock-analysis/_layout/score-input',
)()
const MockAnalysisLayoutScoreAnalysisLazyRouteImport = createFileRoute(
  '/mock-analysis/_layout/score-analysis',
)()
const MockAnalysisLayoutPredictionLazyRouteImport = createFileRoute(
  '/mock-analysis/_layout/prediction',
)()
const GradeAnalysisLayoutSubjectLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/subject',
)()
const GradeAnalysisLayoutSchoolRecordLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/school-record',
)()
const GradeAnalysisLayoutRequestLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/request',
)()
const GradeAnalysisLayoutPerformanceLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/performance',
)()
const GradeAnalysisLayoutNonsulLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/nonsul',
)()
const GradeAnalysisLayoutEvaluationListLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/evaluation-list',
)()
const GradeAnalysisLayoutComprehensiveLazyRouteImport = createFileRoute(
  '/grade-analysis/_layout/comprehensive',
)()
const EvaluationLayoutRequestLazyRouteImport = createFileRoute(
  '/evaluation/_layout/request',
)()
const EvaluationLayoutListLazyRouteImport = createFileRoute(
  '/evaluation/_layout/list',
)()
const EvaluationLayoutCompatibilityLazyRouteImport = createFileRoute(
  '/evaluation/_layout/compatibility',
)()
const UsersLayoutPaymentIndexLazyRouteImport = createFileRoute(
  '/users/_layout/payment/',
)()
const OfficerLayoutApplyIndexLazyRouteImport = createFileRoute(
  '/officer/_layout/apply/',
)()
const EvaluationLayoutSelfIndexLazyRouteImport = createFileRoute(
  '/evaluation/_layout/self/',
)()
const UsersLayoutPaymentIdLazyRouteImport = createFileRoute(
  '/users/_layout/payment/$id',
)()
const OfficerLayoutApplyEvaluationIdLazyRouteImport = createFileRoute(
  '/officer/_layout/apply/$evaluationId',
)()

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const H4Route = H4RouteImport.update({
  id: '/h4',
  path: '/h4',
  getParentRoute: () => rootRouteImport,
} as any)
const H3Route = H3RouteImport.update({
  id: '/h3',
  path: '/h3',
  getParentRoute: () => rootRouteImport,
} as any)
const H2Route = H2RouteImport.update({
  id: '/h2',
  path: '/h2',
  getParentRoute: () => rootRouteImport,
} as any)
const H1Route = H1RouteImport.update({
  id: '/h1',
  path: '/h1',
  getParentRoute: () => rootRouteImport,
} as any)
const TryRouteRoute = TryRouteRouteImport.update({
  id: '/try',
  path: '/try',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoreAnalysisRouteRoute = ScoreAnalysisRouteRouteImport.update({
  id: '/score-analysis',
  path: '/score-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const MsRouteRoute = MsRouteRouteImport.update({
  id: '/ms',
  path: '/ms',
  getParentRoute: () => rootRouteImport,
} as any)
const MockAnalysisRouteRoute = MockAnalysisRouteRouteImport.update({
  id: '/mock-analysis',
  path: '/mock-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const GradeAnalysisRouteRoute = GradeAnalysisRouteRouteImport.update({
  id: '/grade-analysis',
  path: '/grade-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TryIndexLazyRoute = TryIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TryRouteRoute,
} as any).lazy(() => import('./routes/try/index.lazy').then((d) => d.Route))
const ScoreAnalysisIndexLazyRoute = ScoreAnalysisIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScoreAnalysisRouteRoute,
} as any).lazy(() =>
  import('./routes/score-analysis/index.lazy').then((d) => d.Route),
)
const MsIndexLazyRoute = MsIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MsRouteRoute,
} as any).lazy(() => import('./routes/ms/index.lazy').then((d) => d.Route))
const GradeAnalysisIndexLazyRoute = GradeAnalysisIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GradeAnalysisRouteRoute,
} as any).lazy(() =>
  import('./routes/grade-analysis/index.lazy').then((d) => d.Route),
)
const EvaluationIndexLazyRoute = EvaluationIndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EvaluationRoute,
} as any).lazy(() =>
  import('./routes/evaluation/index.lazy').then((d) => d.Route),
)
const AnalysisIndexLazyRoute = AnalysisIndexLazyRouteImport.update({
  id: '/analysis/',
  path: '/analysis/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/analysis/index.lazy').then((d) => d.Route),
)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialGuideLazyRoute = OfficialGuideLazyRouteImport.update({
  id: '/official/guide',
  path: '/official/guide',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/official/guide.lazy').then((d) => d.Route),
)
const OfficialFaqLazyRoute = OfficialFaqLazyRouteImport.update({
  id: '/official/faq',
  path: '/official/faq',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/official/faq.lazy').then((d) => d.Route))
const ExploreSusiKyokwaLazyRoute = ExploreSusiKyokwaLazyRouteImport.update({
  id: '/explore/susi-kyokwa',
  path: '/explore/susi-kyokwa',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explore/susi-kyokwa.lazy').then((d) => d.Route),
)
const ExploreSusiJonghapLazyRoute = ExploreSusiJonghapLazyRouteImport.update({
  id: '/explore/susi-jonghap',
  path: '/explore/susi-jonghap',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explore/susi-jonghap.lazy').then((d) => d.Route),
)
const ExplainServiceLazyRoute = ExplainServiceLazyRouteImport.update({
  id: '/explain/service',
  path: '/explain/service',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explain/service.lazy').then((d) => d.Route),
)
const ExplainRefundLazyRoute = ExplainRefundLazyRouteImport.update({
  id: '/explain/refund',
  path: '/explain/refund',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explain/refund.lazy').then((d) => d.Route),
)
const ExplainPrivacyLazyRoute = ExplainPrivacyLazyRouteImport.update({
  id: '/explain/privacy',
  path: '/explain/privacy',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/explain/privacy.lazy').then((d) => d.Route),
)
const AnalysisPerformanceLazyRoute = AnalysisPerformanceLazyRouteImport.update({
  id: '/analysis/performance',
  path: '/analysis/performance',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/analysis/performance.lazy').then((d) => d.Route),
)
const naverRedirectLazyRoute = naverRedirectLazyRouteImport
  .update({
    id: '/(naver)/redirect',
    path: '/redirect',
    getParentRoute: () => rootRouteImport,
  } as any)
  .lazy(() => import('./routes/(naver)/redirect.lazy').then((d) => d.Route))
const UsersLayoutRoute = UsersLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => UsersRoute,
} as any)
const TestLoginDebugRoute = TestLoginDebugRouteImport.update({
  id: '/test/login-debug',
  path: '/test/login-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const TestAuthMeRoute = TestAuthMeRouteImport.update({
  id: '/test/auth-me',
  path: '/test/auth-me',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderProductIdRoute = OrderProductIdRouteImport.update({
  id: '/order/$productId',
  path: '/order/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerLayoutRoute = OfficerLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => OfficerRoute,
} as any)
const MsLayoutRoute = MsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => MsRouteRoute,
} as any)
const MockAnalysisLayoutRoute = MockAnalysisLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => MockAnalysisRouteRoute,
} as any)
const GradeAnalysisLayoutRoute = GradeAnalysisLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => GradeAnalysisRouteRoute,
} as any)
const ExploreUniversityRoute = ExploreUniversityRouteImport.update({
  id: '/explore/university',
  path: '/explore/university',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRecruitmentUnitRoute = ExploreRecruitmentUnitRouteImport.update({
  id: '/explore/recruitment-unit',
  path: '/explore/recruitment-unit',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreAdmissionRoute = ExploreAdmissionRouteImport.update({
  id: '/explore/admission',
  path: '/explore/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluationLayoutRoute = EvaluationLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => EvaluationRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/auth/reset-password',
  path: '/auth/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialNoticeIndexLazyRoute = OfficialNoticeIndexLazyRouteImport.update({
  id: '/official/notice/',
  path: '/official/notice/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/official/notice.index.lazy').then((d) => d.Route),
)
const UsersLayoutSchoolRecordLazyRoute =
  UsersLayoutSchoolRecordLazyRouteImport.update({
    id: '/school-record',
    path: '/school-record',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/school-record.lazy').then((d) => d.Route),
  )
const UsersLayoutProfileLazyRoute = UsersLayoutProfileLazyRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UsersLayoutRoute,
} as any).lazy(() =>
  import('./routes/users/_layout/profile.lazy').then((d) => d.Route),
)
const UsersLayoutMockExamLazyRoute = UsersLayoutMockExamLazyRouteImport.update({
  id: '/mock-exam',
  path: '/mock-exam',
  getParentRoute: () => UsersLayoutRoute,
} as any).lazy(() =>
  import('./routes/users/_layout/mock-exam.lazy').then((d) => d.Route),
)
const UsersLayoutAdditionalFileLazyRoute =
  UsersLayoutAdditionalFileLazyRouteImport.update({
    id: '/additional-file',
    path: '/additional-file',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/additional-file.lazy').then((d) => d.Route),
  )
const OfficialNoticePostIdLazyRoute =
  OfficialNoticePostIdLazyRouteImport.update({
    id: '/official/notice/$postId',
    path: '/official/notice/$postId',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/official/notice.$postId.lazy').then((d) => d.Route),
  )
const OfficerLayoutProfileLazyRoute =
  OfficerLayoutProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => OfficerLayoutRoute,
  } as any).lazy(() =>
    import('./routes/officer/_layout/profile.lazy').then((d) => d.Route),
  )
const MsLayoutSubjectLazyRoute = MsLayoutSubjectLazyRouteImport.update({
  id: '/subject',
  path: '/subject',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.subject.lazy').then((d) => d.Route),
)
const MsLayoutSetukLazyRoute = MsLayoutSetukLazyRouteImport.update({
  id: '/setuk',
  path: '/setuk',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.setuk.lazy').then((d) => d.Route),
)
const MsLayoutSchoolRecordLazyRoute =
  MsLayoutSchoolRecordLazyRouteImport.update({
    id: '/school-record',
    path: '/school-record',
    getParentRoute: () => MsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/ms/_layout.school-record.lazy').then((d) => d.Route),
  )
const MsLayoutRequestLazyRoute = MsLayoutRequestLazyRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.request.lazy').then((d) => d.Route),
)
const MsLayoutPerformanceLazyRoute = MsLayoutPerformanceLazyRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.performance.lazy').then((d) => d.Route),
)
const MsLayoutNonsulLazyRoute = MsLayoutNonsulLazyRouteImport.update({
  id: '/nonsul',
  path: '/nonsul',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.nonsul.lazy').then((d) => d.Route),
)
const MsLayoutKyokwaLazyRoute = MsLayoutKyokwaLazyRouteImport.update({
  id: '/kyokwa',
  path: '/kyokwa',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.kyokwa.lazy').then((d) => d.Route),
)
const MsLayoutJonghapLazyRoute = MsLayoutJonghapLazyRouteImport.update({
  id: '/jonghap',
  path: '/jonghap',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.jonghap.lazy').then((d) => d.Route),
)
const MsLayoutInterestLazyRoute = MsLayoutInterestLazyRouteImport.update({
  id: '/interest',
  path: '/interest',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.interest.lazy').then((d) => d.Route),
)
const MsLayoutEvaluationListLazyRoute =
  MsLayoutEvaluationListLazyRouteImport.update({
    id: '/evaluation-list',
    path: '/evaluation-list',
    getParentRoute: () => MsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/ms/_layout.evaluation-list.lazy').then((d) => d.Route),
  )
const MsLayoutCreativeActivityLazyRoute =
  MsLayoutCreativeActivityLazyRouteImport.update({
    id: '/creative-activity',
    path: '/creative-activity',
    getParentRoute: () => MsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/ms/_layout.creative-activity.lazy').then((d) => d.Route),
  )
const MsLayoutComprehensiveLazyRoute =
  MsLayoutComprehensiveLazyRouteImport.update({
    id: '/comprehensive',
    path: '/comprehensive',
    getParentRoute: () => MsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/ms/_layout.comprehensive.lazy').then((d) => d.Route),
  )
const MsLayoutCompatibilityLazyRoute =
  MsLayoutCompatibilityLazyRouteImport.update({
    id: '/compatibility',
    path: '/compatibility',
    getParentRoute: () => MsLayoutRoute,
  } as any).lazy(() =>
    import('./routes/ms/_layout.compatibility.lazy').then((d) => d.Route),
  )
const MsLayoutCombinationLazyRoute = MsLayoutCombinationLazyRouteImport.update({
  id: '/combination',
  path: '/combination',
  getParentRoute: () => MsLayoutRoute,
} as any).lazy(() =>
  import('./routes/ms/_layout.combination.lazy').then((d) => d.Route),
)
const MockAnalysisLayoutWrongAnswersLazyRoute =
  MockAnalysisLayoutWrongAnswersLazyRouteImport.update({
    id: '/wrong-answers',
    path: '/wrong-answers',
    getParentRoute: () => MockAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/mock-analysis/_layout.wrong-answers.lazy').then(
      (d) => d.Route,
    ),
  )
const MockAnalysisLayoutTargetUniversityLazyRoute =
  MockAnalysisLayoutTargetUniversityLazyRouteImport.update({
    id: '/target-university',
    path: '/target-university',
    getParentRoute: () => MockAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/mock-analysis/_layout.target-university.lazy').then(
      (d) => d.Route,
    ),
  )
const MockAnalysisLayoutStatisticsLazyRoute =
  MockAnalysisLayoutStatisticsLazyRouteImport.update({
    id: '/statistics',
    path: '/statistics',
    getParentRoute: () => MockAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/mock-analysis/_layout.statistics.lazy').then(
      (d) => d.Route,
    ),
  )
const MockAnalysisLayoutScoreInputLazyRoute =
  MockAnalysisLayoutScoreInputLazyRouteImport.update({
    id: '/score-input',
    path: '/score-input',
    getParentRoute: () => MockAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/mock-analysis/_layout.score-input.lazy').then(
      (d) => d.Route,
    ),
  )
const MockAnalysisLayoutScoreAnalysisLazyRoute =
  MockAnalysisLayoutScoreAnalysisLazyRouteImport.update({
    id: '/score-analysis',
    path: '/score-analysis',
    getParentRoute: () => MockAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/mock-analysis/_layout.score-analysis.lazy').then(
      (d) => d.Route,
    ),
  )
const MockAnalysisLayoutPredictionLazyRoute =
  MockAnalysisLayoutPredictionLazyRouteImport.update({
    id: '/prediction',
    path: '/prediction',
    getParentRoute: () => MockAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/mock-analysis/_layout.prediction.lazy').then(
      (d) => d.Route,
    ),
  )
const GradeAnalysisLayoutSubjectLazyRoute =
  GradeAnalysisLayoutSubjectLazyRouteImport.update({
    id: '/subject',
    path: '/subject',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.subject.lazy').then((d) => d.Route),
  )
const GradeAnalysisLayoutSchoolRecordLazyRoute =
  GradeAnalysisLayoutSchoolRecordLazyRouteImport.update({
    id: '/school-record',
    path: '/school-record',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.school-record.lazy').then(
      (d) => d.Route,
    ),
  )
const GradeAnalysisLayoutRequestLazyRoute =
  GradeAnalysisLayoutRequestLazyRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.request.lazy').then((d) => d.Route),
  )
const GradeAnalysisLayoutPerformanceLazyRoute =
  GradeAnalysisLayoutPerformanceLazyRouteImport.update({
    id: '/performance',
    path: '/performance',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.performance.lazy').then(
      (d) => d.Route,
    ),
  )
const GradeAnalysisLayoutNonsulLazyRoute =
  GradeAnalysisLayoutNonsulLazyRouteImport.update({
    id: '/nonsul',
    path: '/nonsul',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.nonsul.lazy').then((d) => d.Route),
  )
const GradeAnalysisLayoutEvaluationListLazyRoute =
  GradeAnalysisLayoutEvaluationListLazyRouteImport.update({
    id: '/evaluation-list',
    path: '/evaluation-list',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.evaluation-list.lazy').then(
      (d) => d.Route,
    ),
  )
const GradeAnalysisLayoutComprehensiveLazyRoute =
  GradeAnalysisLayoutComprehensiveLazyRouteImport.update({
    id: '/comprehensive',
    path: '/comprehensive',
    getParentRoute: () => GradeAnalysisLayoutRoute,
  } as any).lazy(() =>
    import('./routes/grade-analysis/_layout.comprehensive.lazy').then(
      (d) => d.Route,
    ),
  )
const EvaluationLayoutRequestLazyRoute =
  EvaluationLayoutRequestLazyRouteImport.update({
    id: '/request',
    path: '/request',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/request.lazy').then((d) => d.Route),
  )
const EvaluationLayoutListLazyRoute =
  EvaluationLayoutListLazyRouteImport.update({
    id: '/list',
    path: '/list',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/list.lazy').then((d) => d.Route),
  )
const EvaluationLayoutCompatibilityLazyRoute =
  EvaluationLayoutCompatibilityLazyRouteImport.update({
    id: '/compatibility',
    path: '/compatibility',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/compatibility.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthOauthCallbackRoute = AuthOauthCallbackRouteImport.update({
  id: '/auth/oauth/callback',
  path: '/auth/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersLayoutPaymentIndexLazyRoute =
  UsersLayoutPaymentIndexLazyRouteImport.update({
    id: '/payment/',
    path: '/payment/',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/payment.index.lazy').then((d) => d.Route),
  )
const OfficerLayoutApplyIndexLazyRoute =
  OfficerLayoutApplyIndexLazyRouteImport.update({
    id: '/apply/',
    path: '/apply/',
    getParentRoute: () => OfficerLayoutRoute,
  } as any).lazy(() =>
    import('./routes/officer/_layout/apply.index.lazy').then((d) => d.Route),
  )
const EvaluationLayoutSelfIndexLazyRoute =
  EvaluationLayoutSelfIndexLazyRouteImport.update({
    id: '/self/',
    path: '/self/',
    getParentRoute: () => EvaluationLayoutRoute,
  } as any).lazy(() =>
    import('./routes/evaluation/_layout/self.index.lazy').then((d) => d.Route),
  )
const UsersLayoutPaymentIdLazyRoute =
  UsersLayoutPaymentIdLazyRouteImport.update({
    id: '/payment/$id',
    path: '/payment/$id',
    getParentRoute: () => UsersLayoutRoute,
  } as any).lazy(() =>
    import('./routes/users/_layout/payment.$id.lazy').then((d) => d.Route),
  )
const OfficerLayoutApplyEvaluationIdLazyRoute =
  OfficerLayoutApplyEvaluationIdLazyRouteImport.update({
    id: '/apply/$evaluationId',
    path: '/apply/$evaluationId',
    getParentRoute: () => OfficerLayoutRoute,
  } as any).lazy(() =>
    import('./routes/officer/_layout/apply.$evaluationId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/grade-analysis': typeof GradeAnalysisLayoutRouteWithChildren
  '/mock-analysis': typeof MockAnalysisLayoutRouteWithChildren
  '/ms': typeof MsLayoutRouteWithChildren
  '/score-analysis': typeof ScoreAnalysisRouteRouteWithChildren
  '/try': typeof TryRouteRouteWithChildren
  '/h1': typeof H1Route
  '/h2': typeof H2Route
  '/h3': typeof H3Route
  '/h4': typeof H4Route
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/evaluation': typeof EvaluationLayoutRouteWithChildren
  '/explore/admission': typeof ExploreAdmissionRoute
  '/explore/recruitment-unit': typeof ExploreRecruitmentUnitRoute
  '/explore/university': typeof ExploreUniversityRoute
  '/officer': typeof OfficerLayoutRouteWithChildren
  '/order/$productId': typeof OrderProductIdRoute
  '/test/auth-me': typeof TestAuthMeRoute
  '/test/login-debug': typeof TestLoginDebugRoute
  '/users': typeof UsersLayoutRouteWithChildren
  '/redirect': typeof naverRedirectLazyRoute
  '/analysis/performance': typeof AnalysisPerformanceLazyRoute
  '/explain/privacy': typeof ExplainPrivacyLazyRoute
  '/explain/refund': typeof ExplainRefundLazyRoute
  '/explain/service': typeof ExplainServiceLazyRoute
  '/explore/susi-jonghap': typeof ExploreSusiJonghapLazyRoute
  '/explore/susi-kyokwa': typeof ExploreSusiKyokwaLazyRoute
  '/official/faq': typeof OfficialFaqLazyRoute
  '/official/guide': typeof OfficialGuideLazyRoute
  '/products': typeof ProductsIndexRoute
  '/analysis': typeof AnalysisIndexLazyRoute
  '/evaluation/': typeof EvaluationIndexLazyRoute
  '/grade-analysis/': typeof GradeAnalysisIndexLazyRoute
  '/ms/': typeof MsIndexLazyRoute
  '/score-analysis/': typeof ScoreAnalysisIndexLazyRoute
  '/try/': typeof TryIndexLazyRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/evaluation/compatibility': typeof EvaluationLayoutCompatibilityLazyRoute
  '/evaluation/list': typeof EvaluationLayoutListLazyRoute
  '/evaluation/request': typeof EvaluationLayoutRequestLazyRoute
  '/grade-analysis/comprehensive': typeof GradeAnalysisLayoutComprehensiveLazyRoute
  '/grade-analysis/evaluation-list': typeof GradeAnalysisLayoutEvaluationListLazyRoute
  '/grade-analysis/nonsul': typeof GradeAnalysisLayoutNonsulLazyRoute
  '/grade-analysis/performance': typeof GradeAnalysisLayoutPerformanceLazyRoute
  '/grade-analysis/request': typeof GradeAnalysisLayoutRequestLazyRoute
  '/grade-analysis/school-record': typeof GradeAnalysisLayoutSchoolRecordLazyRoute
  '/grade-analysis/subject': typeof GradeAnalysisLayoutSubjectLazyRoute
  '/mock-analysis/prediction': typeof MockAnalysisLayoutPredictionLazyRoute
  '/mock-analysis/score-analysis': typeof MockAnalysisLayoutScoreAnalysisLazyRoute
  '/mock-analysis/score-input': typeof MockAnalysisLayoutScoreInputLazyRoute
  '/mock-analysis/statistics': typeof MockAnalysisLayoutStatisticsLazyRoute
  '/mock-analysis/target-university': typeof MockAnalysisLayoutTargetUniversityLazyRoute
  '/mock-analysis/wrong-answers': typeof MockAnalysisLayoutWrongAnswersLazyRoute
  '/ms/combination': typeof MsLayoutCombinationLazyRoute
  '/ms/compatibility': typeof MsLayoutCompatibilityLazyRoute
  '/ms/comprehensive': typeof MsLayoutComprehensiveLazyRoute
  '/ms/creative-activity': typeof MsLayoutCreativeActivityLazyRoute
  '/ms/evaluation-list': typeof MsLayoutEvaluationListLazyRoute
  '/ms/interest': typeof MsLayoutInterestLazyRoute
  '/ms/jonghap': typeof MsLayoutJonghapLazyRoute
  '/ms/kyokwa': typeof MsLayoutKyokwaLazyRoute
  '/ms/nonsul': typeof MsLayoutNonsulLazyRoute
  '/ms/performance': typeof MsLayoutPerformanceLazyRoute
  '/ms/request': typeof MsLayoutRequestLazyRoute
  '/ms/school-record': typeof MsLayoutSchoolRecordLazyRoute
  '/ms/setuk': typeof MsLayoutSetukLazyRoute
  '/ms/subject': typeof MsLayoutSubjectLazyRoute
  '/officer/profile': typeof OfficerLayoutProfileLazyRoute
  '/official/notice/$postId': typeof OfficialNoticePostIdLazyRoute
  '/users/additional-file': typeof UsersLayoutAdditionalFileLazyRoute
  '/users/mock-exam': typeof UsersLayoutMockExamLazyRoute
  '/users/profile': typeof UsersLayoutProfileLazyRoute
  '/users/school-record': typeof UsersLayoutSchoolRecordLazyRoute
  '/official/notice': typeof OfficialNoticeIndexLazyRoute
  '/officer/apply/$evaluationId': typeof OfficerLayoutApplyEvaluationIdLazyRoute
  '/users/payment/$id': typeof UsersLayoutPaymentIdLazyRoute
  '/evaluation/self': typeof EvaluationLayoutSelfIndexLazyRoute
  '/officer/apply': typeof OfficerLayoutApplyIndexLazyRoute
  '/users/payment': typeof UsersLayoutPaymentIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mock-analysis': typeof MockAnalysisLayoutRouteWithChildren
  '/h1': typeof H1Route
  '/h2': typeof H2Route
  '/h3': typeof H3Route
  '/h4': typeof H4Route
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/evaluation': typeof EvaluationIndexLazyRoute
  '/explore/admission': typeof ExploreAdmissionRoute
  '/explore/recruitment-unit': typeof ExploreRecruitmentUnitRoute
  '/explore/university': typeof ExploreUniversityRoute
  '/grade-analysis': typeof GradeAnalysisIndexLazyRoute
  '/ms': typeof MsIndexLazyRoute
  '/officer': typeof OfficerLayoutRouteWithChildren
  '/order/$productId': typeof OrderProductIdRoute
  '/test/auth-me': typeof TestAuthMeRoute
  '/test/login-debug': typeof TestLoginDebugRoute
  '/users': typeof UsersLayoutRouteWithChildren
  '/redirect': typeof naverRedirectLazyRoute
  '/analysis/performance': typeof AnalysisPerformanceLazyRoute
  '/explain/privacy': typeof ExplainPrivacyLazyRoute
  '/explain/refund': typeof ExplainRefundLazyRoute
  '/explain/service': typeof ExplainServiceLazyRoute
  '/explore/susi-jonghap': typeof ExploreSusiJonghapLazyRoute
  '/explore/susi-kyokwa': typeof ExploreSusiKyokwaLazyRoute
  '/official/faq': typeof OfficialFaqLazyRoute
  '/official/guide': typeof OfficialGuideLazyRoute
  '/products': typeof ProductsIndexRoute
  '/analysis': typeof AnalysisIndexLazyRoute
  '/score-analysis': typeof ScoreAnalysisIndexLazyRoute
  '/try': typeof TryIndexLazyRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/evaluation/compatibility': typeof EvaluationLayoutCompatibilityLazyRoute
  '/evaluation/list': typeof EvaluationLayoutListLazyRoute
  '/evaluation/request': typeof EvaluationLayoutRequestLazyRoute
  '/grade-analysis/comprehensive': typeof GradeAnalysisLayoutComprehensiveLazyRoute
  '/grade-analysis/evaluation-list': typeof GradeAnalysisLayoutEvaluationListLazyRoute
  '/grade-analysis/nonsul': typeof GradeAnalysisLayoutNonsulLazyRoute
  '/grade-analysis/performance': typeof GradeAnalysisLayoutPerformanceLazyRoute
  '/grade-analysis/request': typeof GradeAnalysisLayoutRequestLazyRoute
  '/grade-analysis/school-record': typeof GradeAnalysisLayoutSchoolRecordLazyRoute
  '/grade-analysis/subject': typeof GradeAnalysisLayoutSubjectLazyRoute
  '/mock-analysis/prediction': typeof MockAnalysisLayoutPredictionLazyRoute
  '/mock-analysis/score-analysis': typeof MockAnalysisLayoutScoreAnalysisLazyRoute
  '/mock-analysis/score-input': typeof MockAnalysisLayoutScoreInputLazyRoute
  '/mock-analysis/statistics': typeof MockAnalysisLayoutStatisticsLazyRoute
  '/mock-analysis/target-university': typeof MockAnalysisLayoutTargetUniversityLazyRoute
  '/mock-analysis/wrong-answers': typeof MockAnalysisLayoutWrongAnswersLazyRoute
  '/ms/combination': typeof MsLayoutCombinationLazyRoute
  '/ms/compatibility': typeof MsLayoutCompatibilityLazyRoute
  '/ms/comprehensive': typeof MsLayoutComprehensiveLazyRoute
  '/ms/creative-activity': typeof MsLayoutCreativeActivityLazyRoute
  '/ms/evaluation-list': typeof MsLayoutEvaluationListLazyRoute
  '/ms/interest': typeof MsLayoutInterestLazyRoute
  '/ms/jonghap': typeof MsLayoutJonghapLazyRoute
  '/ms/kyokwa': typeof MsLayoutKyokwaLazyRoute
  '/ms/nonsul': typeof MsLayoutNonsulLazyRoute
  '/ms/performance': typeof MsLayoutPerformanceLazyRoute
  '/ms/request': typeof MsLayoutRequestLazyRoute
  '/ms/school-record': typeof MsLayoutSchoolRecordLazyRoute
  '/ms/setuk': typeof MsLayoutSetukLazyRoute
  '/ms/subject': typeof MsLayoutSubjectLazyRoute
  '/officer/profile': typeof OfficerLayoutProfileLazyRoute
  '/official/notice/$postId': typeof OfficialNoticePostIdLazyRoute
  '/users/additional-file': typeof UsersLayoutAdditionalFileLazyRoute
  '/users/mock-exam': typeof UsersLayoutMockExamLazyRoute
  '/users/profile': typeof UsersLayoutProfileLazyRoute
  '/users/school-record': typeof UsersLayoutSchoolRecordLazyRoute
  '/official/notice': typeof OfficialNoticeIndexLazyRoute
  '/officer/apply/$evaluationId': typeof OfficerLayoutApplyEvaluationIdLazyRoute
  '/users/payment/$id': typeof UsersLayoutPaymentIdLazyRoute
  '/evaluation/self': typeof EvaluationLayoutSelfIndexLazyRoute
  '/officer/apply': typeof OfficerLayoutApplyIndexLazyRoute
  '/users/payment': typeof UsersLayoutPaymentIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/grade-analysis': typeof GradeAnalysisRouteRouteWithChildren
  '/mock-analysis': typeof MockAnalysisRouteRouteWithChildren
  '/ms': typeof MsRouteRouteWithChildren
  '/score-analysis': typeof ScoreAnalysisRouteRouteWithChildren
  '/try': typeof TryRouteRouteWithChildren
  '/h1': typeof H1Route
  '/h2': typeof H2Route
  '/h3': typeof H3Route
  '/h4': typeof H4Route
  '/pricing': typeof PricingRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/evaluation/_layout': typeof EvaluationLayoutRouteWithChildren
  '/explore/admission': typeof ExploreAdmissionRoute
  '/explore/recruitment-unit': typeof ExploreRecruitmentUnitRoute
  '/explore/university': typeof ExploreUniversityRoute
  '/grade-analysis/_layout': typeof GradeAnalysisLayoutRouteWithChildren
  '/mock-analysis/_layout': typeof MockAnalysisLayoutRouteWithChildren
  '/ms/_layout': typeof MsLayoutRouteWithChildren
  '/officer/_layout': typeof OfficerLayoutRouteWithChildren
  '/order/$productId': typeof OrderProductIdRoute
  '/test/auth-me': typeof TestAuthMeRoute
  '/test/login-debug': typeof TestLoginDebugRoute
  '/users/_layout': typeof UsersLayoutRouteWithChildren
  '/(naver)/redirect': typeof naverRedirectLazyRoute
  '/analysis/performance': typeof AnalysisPerformanceLazyRoute
  '/explain/privacy': typeof ExplainPrivacyLazyRoute
  '/explain/refund': typeof ExplainRefundLazyRoute
  '/explain/service': typeof ExplainServiceLazyRoute
  '/explore/susi-jonghap': typeof ExploreSusiJonghapLazyRoute
  '/explore/susi-kyokwa': typeof ExploreSusiKyokwaLazyRoute
  '/official/faq': typeof OfficialFaqLazyRoute
  '/official/guide': typeof OfficialGuideLazyRoute
  '/products/': typeof ProductsIndexRoute
  '/analysis/': typeof AnalysisIndexLazyRoute
  '/evaluation/': typeof EvaluationIndexLazyRoute
  '/grade-analysis/': typeof GradeAnalysisIndexLazyRoute
  '/ms/': typeof MsIndexLazyRoute
  '/score-analysis/': typeof ScoreAnalysisIndexLazyRoute
  '/try/': typeof TryIndexLazyRoute
  '/auth/oauth/callback': typeof AuthOauthCallbackRoute
  '/evaluation/_layout/compatibility': typeof EvaluationLayoutCompatibilityLazyRoute
  '/evaluation/_layout/list': typeof EvaluationLayoutListLazyRoute
  '/evaluation/_layout/request': typeof EvaluationLayoutRequestLazyRoute
  '/grade-analysis/_layout/comprehensive': typeof GradeAnalysisLayoutComprehensiveLazyRoute
  '/grade-analysis/_layout/evaluation-list': typeof GradeAnalysisLayoutEvaluationListLazyRoute
  '/grade-analysis/_layout/nonsul': typeof GradeAnalysisLayoutNonsulLazyRoute
  '/grade-analysis/_layout/performance': typeof GradeAnalysisLayoutPerformanceLazyRoute
  '/grade-analysis/_layout/request': typeof GradeAnalysisLayoutRequestLazyRoute
  '/grade-analysis/_layout/school-record': typeof GradeAnalysisLayoutSchoolRecordLazyRoute
  '/grade-analysis/_layout/subject': typeof GradeAnalysisLayoutSubjectLazyRoute
  '/mock-analysis/_layout/prediction': typeof MockAnalysisLayoutPredictionLazyRoute
  '/mock-analysis/_layout/score-analysis': typeof MockAnalysisLayoutScoreAnalysisLazyRoute
  '/mock-analysis/_layout/score-input': typeof MockAnalysisLayoutScoreInputLazyRoute
  '/mock-analysis/_layout/statistics': typeof MockAnalysisLayoutStatisticsLazyRoute
  '/mock-analysis/_layout/target-university': typeof MockAnalysisLayoutTargetUniversityLazyRoute
  '/mock-analysis/_layout/wrong-answers': typeof MockAnalysisLayoutWrongAnswersLazyRoute
  '/ms/_layout/combination': typeof MsLayoutCombinationLazyRoute
  '/ms/_layout/compatibility': typeof MsLayoutCompatibilityLazyRoute
  '/ms/_layout/comprehensive': typeof MsLayoutComprehensiveLazyRoute
  '/ms/_layout/creative-activity': typeof MsLayoutCreativeActivityLazyRoute
  '/ms/_layout/evaluation-list': typeof MsLayoutEvaluationListLazyRoute
  '/ms/_layout/interest': typeof MsLayoutInterestLazyRoute
  '/ms/_layout/jonghap': typeof MsLayoutJonghapLazyRoute
  '/ms/_layout/kyokwa': typeof MsLayoutKyokwaLazyRoute
  '/ms/_layout/nonsul': typeof MsLayoutNonsulLazyRoute
  '/ms/_layout/performance': typeof MsLayoutPerformanceLazyRoute
  '/ms/_layout/request': typeof MsLayoutRequestLazyRoute
  '/ms/_layout/school-record': typeof MsLayoutSchoolRecordLazyRoute
  '/ms/_layout/setuk': typeof MsLayoutSetukLazyRoute
  '/ms/_layout/subject': typeof MsLayoutSubjectLazyRoute
  '/officer/_layout/profile': typeof OfficerLayoutProfileLazyRoute
  '/official/notice/$postId': typeof OfficialNoticePostIdLazyRoute
  '/users/_layout/additional-file': typeof UsersLayoutAdditionalFileLazyRoute
  '/users/_layout/mock-exam': typeof UsersLayoutMockExamLazyRoute
  '/users/_layout/profile': typeof UsersLayoutProfileLazyRoute
  '/users/_layout/school-record': typeof UsersLayoutSchoolRecordLazyRoute
  '/official/notice/': typeof OfficialNoticeIndexLazyRoute
  '/officer/_layout/apply/$evaluationId': typeof OfficerLayoutApplyEvaluationIdLazyRoute
  '/users/_layout/payment/$id': typeof UsersLayoutPaymentIdLazyRoute
  '/evaluation/_layout/self/': typeof EvaluationLayoutSelfIndexLazyRoute
  '/officer/_layout/apply/': typeof OfficerLayoutApplyIndexLazyRoute
  '/users/_layout/payment/': typeof UsersLayoutPaymentIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/grade-analysis'
    | '/mock-analysis'
    | '/ms'
    | '/score-analysis'
    | '/try'
    | '/h1'
    | '/h2'
    | '/h3'
    | '/h4'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/evaluation'
    | '/explore/admission'
    | '/explore/recruitment-unit'
    | '/explore/university'
    | '/officer'
    | '/order/$productId'
    | '/test/auth-me'
    | '/test/login-debug'
    | '/users'
    | '/redirect'
    | '/analysis/performance'
    | '/explain/privacy'
    | '/explain/refund'
    | '/explain/service'
    | '/explore/susi-jonghap'
    | '/explore/susi-kyokwa'
    | '/official/faq'
    | '/official/guide'
    | '/products'
    | '/analysis'
    | '/evaluation/'
    | '/grade-analysis/'
    | '/ms/'
    | '/score-analysis/'
    | '/try/'
    | '/auth/oauth/callback'
    | '/evaluation/compatibility'
    | '/evaluation/list'
    | '/evaluation/request'
    | '/grade-analysis/comprehensive'
    | '/grade-analysis/evaluation-list'
    | '/grade-analysis/nonsul'
    | '/grade-analysis/performance'
    | '/grade-analysis/request'
    | '/grade-analysis/school-record'
    | '/grade-analysis/subject'
    | '/mock-analysis/prediction'
    | '/mock-analysis/score-analysis'
    | '/mock-analysis/score-input'
    | '/mock-analysis/statistics'
    | '/mock-analysis/target-university'
    | '/mock-analysis/wrong-answers'
    | '/ms/combination'
    | '/ms/compatibility'
    | '/ms/comprehensive'
    | '/ms/creative-activity'
    | '/ms/evaluation-list'
    | '/ms/interest'
    | '/ms/jonghap'
    | '/ms/kyokwa'
    | '/ms/nonsul'
    | '/ms/performance'
    | '/ms/request'
    | '/ms/school-record'
    | '/ms/setuk'
    | '/ms/subject'
    | '/officer/profile'
    | '/official/notice/$postId'
    | '/users/additional-file'
    | '/users/mock-exam'
    | '/users/profile'
    | '/users/school-record'
    | '/official/notice'
    | '/officer/apply/$evaluationId'
    | '/users/payment/$id'
    | '/evaluation/self'
    | '/officer/apply'
    | '/users/payment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mock-analysis'
    | '/h1'
    | '/h2'
    | '/h3'
    | '/h4'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/evaluation'
    | '/explore/admission'
    | '/explore/recruitment-unit'
    | '/explore/university'
    | '/grade-analysis'
    | '/ms'
    | '/officer'
    | '/order/$productId'
    | '/test/auth-me'
    | '/test/login-debug'
    | '/users'
    | '/redirect'
    | '/analysis/performance'
    | '/explain/privacy'
    | '/explain/refund'
    | '/explain/service'
    | '/explore/susi-jonghap'
    | '/explore/susi-kyokwa'
    | '/official/faq'
    | '/official/guide'
    | '/products'
    | '/analysis'
    | '/score-analysis'
    | '/try'
    | '/auth/oauth/callback'
    | '/evaluation/compatibility'
    | '/evaluation/list'
    | '/evaluation/request'
    | '/grade-analysis/comprehensive'
    | '/grade-analysis/evaluation-list'
    | '/grade-analysis/nonsul'
    | '/grade-analysis/performance'
    | '/grade-analysis/request'
    | '/grade-analysis/school-record'
    | '/grade-analysis/subject'
    | '/mock-analysis/prediction'
    | '/mock-analysis/score-analysis'
    | '/mock-analysis/score-input'
    | '/mock-analysis/statistics'
    | '/mock-analysis/target-university'
    | '/mock-analysis/wrong-answers'
    | '/ms/combination'
    | '/ms/compatibility'
    | '/ms/comprehensive'
    | '/ms/creative-activity'
    | '/ms/evaluation-list'
    | '/ms/interest'
    | '/ms/jonghap'
    | '/ms/kyokwa'
    | '/ms/nonsul'
    | '/ms/performance'
    | '/ms/request'
    | '/ms/school-record'
    | '/ms/setuk'
    | '/ms/subject'
    | '/officer/profile'
    | '/official/notice/$postId'
    | '/users/additional-file'
    | '/users/mock-exam'
    | '/users/profile'
    | '/users/school-record'
    | '/official/notice'
    | '/officer/apply/$evaluationId'
    | '/users/payment/$id'
    | '/evaluation/self'
    | '/officer/apply'
    | '/users/payment'
  id:
    | '__root__'
    | '/'
    | '/grade-analysis'
    | '/mock-analysis'
    | '/ms'
    | '/score-analysis'
    | '/try'
    | '/h1'
    | '/h2'
    | '/h3'
    | '/h4'
    | '/pricing'
    | '/auth/login'
    | '/auth/register'
    | '/auth/reset-password'
    | '/evaluation/_layout'
    | '/explore/admission'
    | '/explore/recruitment-unit'
    | '/explore/university'
    | '/grade-analysis/_layout'
    | '/mock-analysis/_layout'
    | '/ms/_layout'
    | '/officer/_layout'
    | '/order/$productId'
    | '/test/auth-me'
    | '/test/login-debug'
    | '/users/_layout'
    | '/(naver)/redirect'
    | '/analysis/performance'
    | '/explain/privacy'
    | '/explain/refund'
    | '/explain/service'
    | '/explore/susi-jonghap'
    | '/explore/susi-kyokwa'
    | '/official/faq'
    | '/official/guide'
    | '/products/'
    | '/analysis/'
    | '/evaluation/'
    | '/grade-analysis/'
    | '/ms/'
    | '/score-analysis/'
    | '/try/'
    | '/auth/oauth/callback'
    | '/evaluation/_layout/compatibility'
    | '/evaluation/_layout/list'
    | '/evaluation/_layout/request'
    | '/grade-analysis/_layout/comprehensive'
    | '/grade-analysis/_layout/evaluation-list'
    | '/grade-analysis/_layout/nonsul'
    | '/grade-analysis/_layout/performance'
    | '/grade-analysis/_layout/request'
    | '/grade-analysis/_layout/school-record'
    | '/grade-analysis/_layout/subject'
    | '/mock-analysis/_layout/prediction'
    | '/mock-analysis/_layout/score-analysis'
    | '/mock-analysis/_layout/score-input'
    | '/mock-analysis/_layout/statistics'
    | '/mock-analysis/_layout/target-university'
    | '/mock-analysis/_layout/wrong-answers'
    | '/ms/_layout/combination'
    | '/ms/_layout/compatibility'
    | '/ms/_layout/comprehensive'
    | '/ms/_layout/creative-activity'
    | '/ms/_layout/evaluation-list'
    | '/ms/_layout/interest'
    | '/ms/_layout/jonghap'
    | '/ms/_layout/kyokwa'
    | '/ms/_layout/nonsul'
    | '/ms/_layout/performance'
    | '/ms/_layout/request'
    | '/ms/_layout/school-record'
    | '/ms/_layout/setuk'
    | '/ms/_layout/subject'
    | '/officer/_layout/profile'
    | '/official/notice/$postId'
    | '/users/_layout/additional-file'
    | '/users/_layout/mock-exam'
    | '/users/_layout/profile'
    | '/users/_layout/school-record'
    | '/official/notice/'
    | '/officer/_layout/apply/$evaluationId'
    | '/users/_layout/payment/$id'
    | '/evaluation/_layout/self/'
    | '/officer/_layout/apply/'
    | '/users/_layout/payment/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GradeAnalysisRouteRoute: typeof GradeAnalysisRouteRouteWithChildren
  MockAnalysisRouteRoute: typeof MockAnalysisRouteRouteWithChildren
  MsRouteRoute: typeof MsRouteRouteWithChildren
  ScoreAnalysisRouteRoute: typeof ScoreAnalysisRouteRouteWithChildren
  TryRouteRoute: typeof TryRouteRouteWithChildren
  H1Route: typeof H1Route
  H2Route: typeof H2Route
  H3Route: typeof H3Route
  H4Route: typeof H4Route
  PricingRoute: typeof PricingRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  ExploreAdmissionRoute: typeof ExploreAdmissionRoute
  ExploreRecruitmentUnitRoute: typeof ExploreRecruitmentUnitRoute
  ExploreUniversityRoute: typeof ExploreUniversityRoute
  OrderProductIdRoute: typeof OrderProductIdRoute
  TestAuthMeRoute: typeof TestAuthMeRoute
  TestLoginDebugRoute: typeof TestLoginDebugRoute
  naverRedirectLazyRoute: typeof naverRedirectLazyRoute
  AnalysisPerformanceLazyRoute: typeof AnalysisPerformanceLazyRoute
  ExplainPrivacyLazyRoute: typeof ExplainPrivacyLazyRoute
  ExplainRefundLazyRoute: typeof ExplainRefundLazyRoute
  ExplainServiceLazyRoute: typeof ExplainServiceLazyRoute
  ExploreSusiJonghapLazyRoute: typeof ExploreSusiJonghapLazyRoute
  ExploreSusiKyokwaLazyRoute: typeof ExploreSusiKyokwaLazyRoute
  OfficialFaqLazyRoute: typeof OfficialFaqLazyRoute
  OfficialGuideLazyRoute: typeof OfficialGuideLazyRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  AnalysisIndexLazyRoute: typeof AnalysisIndexLazyRoute
  AuthOauthCallbackRoute: typeof AuthOauthCallbackRoute
  OfficialNoticePostIdLazyRoute: typeof OfficialNoticePostIdLazyRoute
  OfficialNoticeIndexLazyRoute: typeof OfficialNoticeIndexLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h4': {
      id: '/h4'
      path: '/h4'
      fullPath: '/h4'
      preLoaderRoute: typeof H4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h3': {
      id: '/h3'
      path: '/h3'
      fullPath: '/h3'
      preLoaderRoute: typeof H3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h2': {
      id: '/h2'
      path: '/h2'
      fullPath: '/h2'
      preLoaderRoute: typeof H2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/h1': {
      id: '/h1'
      path: '/h1'
      fullPath: '/h1'
      preLoaderRoute: typeof H1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try': {
      id: '/try'
      path: '/try'
      fullPath: '/try'
      preLoaderRoute: typeof TryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/score-analysis': {
      id: '/score-analysis'
      path: '/score-analysis'
      fullPath: '/score-analysis'
      preLoaderRoute: typeof ScoreAnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ms': {
      id: '/ms'
      path: '/ms'
      fullPath: '/ms'
      preLoaderRoute: typeof MsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-analysis': {
      id: '/mock-analysis'
      path: '/mock-analysis'
      fullPath: '/mock-analysis'
      preLoaderRoute: typeof MockAnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grade-analysis': {
      id: '/grade-analysis'
      path: '/grade-analysis'
      fullPath: '/grade-analysis'
      preLoaderRoute: typeof GradeAnalysisRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/try/': {
      id: '/try/'
      path: '/'
      fullPath: '/try/'
      preLoaderRoute: typeof TryIndexLazyRouteImport
      parentRoute: typeof TryRouteRoute
    }
    '/score-analysis/': {
      id: '/score-analysis/'
      path: '/'
      fullPath: '/score-analysis/'
      preLoaderRoute: typeof ScoreAnalysisIndexLazyRouteImport
      parentRoute: typeof ScoreAnalysisRouteRoute
    }
    '/ms/': {
      id: '/ms/'
      path: '/'
      fullPath: '/ms/'
      preLoaderRoute: typeof MsIndexLazyRouteImport
      parentRoute: typeof MsRouteRoute
    }
    '/grade-analysis/': {
      id: '/grade-analysis/'
      path: '/'
      fullPath: '/grade-analysis/'
      preLoaderRoute: typeof GradeAnalysisIndexLazyRouteImport
      parentRoute: typeof GradeAnalysisRouteRoute
    }
    '/evaluation/': {
      id: '/evaluation/'
      path: '/'
      fullPath: '/evaluation/'
      preLoaderRoute: typeof EvaluationIndexLazyRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official/guide': {
      id: '/official/guide'
      path: '/official/guide'
      fullPath: '/official/guide'
      preLoaderRoute: typeof OfficialGuideLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official/faq': {
      id: '/official/faq'
      path: '/official/faq'
      fullPath: '/official/faq'
      preLoaderRoute: typeof OfficialFaqLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/susi-kyokwa': {
      id: '/explore/susi-kyokwa'
      path: '/explore/susi-kyokwa'
      fullPath: '/explore/susi-kyokwa'
      preLoaderRoute: typeof ExploreSusiKyokwaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/susi-jonghap': {
      id: '/explore/susi-jonghap'
      path: '/explore/susi-jonghap'
      fullPath: '/explore/susi-jonghap'
      preLoaderRoute: typeof ExploreSusiJonghapLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/service': {
      id: '/explain/service'
      path: '/explain/service'
      fullPath: '/explain/service'
      preLoaderRoute: typeof ExplainServiceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/refund': {
      id: '/explain/refund'
      path: '/explain/refund'
      fullPath: '/explain/refund'
      preLoaderRoute: typeof ExplainRefundLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explain/privacy': {
      id: '/explain/privacy'
      path: '/explain/privacy'
      fullPath: '/explain/privacy'
      preLoaderRoute: typeof ExplainPrivacyLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/performance': {
      id: '/analysis/performance'
      path: '/analysis/performance'
      fullPath: '/analysis/performance'
      preLoaderRoute: typeof AnalysisPerformanceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(naver)/redirect': {
      id: '/(naver)/redirect'
      path: '/redirect'
      fullPath: '/redirect'
      preLoaderRoute: typeof naverRedirectLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/_layout': {
      id: '/users/_layout'
      path: ''
      fullPath: '/users'
      preLoaderRoute: typeof UsersLayoutRouteImport
      parentRoute: typeof UsersRoute
    }
    '/test/login-debug': {
      id: '/test/login-debug'
      path: '/test/login-debug'
      fullPath: '/test/login-debug'
      preLoaderRoute: typeof TestLoginDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/auth-me': {
      id: '/test/auth-me'
      path: '/test/auth-me'
      fullPath: '/test/auth-me'
      preLoaderRoute: typeof TestAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$productId': {
      id: '/order/$productId'
      path: '/order/$productId'
      fullPath: '/order/$productId'
      preLoaderRoute: typeof OrderProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/_layout': {
      id: '/officer/_layout'
      path: ''
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerLayoutRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/ms/_layout': {
      id: '/ms/_layout'
      path: ''
      fullPath: '/ms'
      preLoaderRoute: typeof MsLayoutRouteImport
      parentRoute: typeof MsRouteRoute
    }
    '/mock-analysis/_layout': {
      id: '/mock-analysis/_layout'
      path: ''
      fullPath: '/mock-analysis'
      preLoaderRoute: typeof MockAnalysisLayoutRouteImport
      parentRoute: typeof MockAnalysisRouteRoute
    }
    '/grade-analysis/_layout': {
      id: '/grade-analysis/_layout'
      path: ''
      fullPath: '/grade-analysis'
      preLoaderRoute: typeof GradeAnalysisLayoutRouteImport
      parentRoute: typeof GradeAnalysisRouteRoute
    }
    '/explore/university': {
      id: '/explore/university'
      path: '/explore/university'
      fullPath: '/explore/university'
      preLoaderRoute: typeof ExploreUniversityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/recruitment-unit': {
      id: '/explore/recruitment-unit'
      path: '/explore/recruitment-unit'
      fullPath: '/explore/recruitment-unit'
      preLoaderRoute: typeof ExploreRecruitmentUnitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/admission': {
      id: '/explore/admission'
      path: '/explore/admission'
      fullPath: '/explore/admission'
      preLoaderRoute: typeof ExploreAdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluation/_layout': {
      id: '/evaluation/_layout'
      path: ''
      fullPath: '/evaluation'
      preLoaderRoute: typeof EvaluationLayoutRouteImport
      parentRoute: typeof EvaluationRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/auth/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official/notice/': {
      id: '/official/notice/'
      path: '/official/notice'
      fullPath: '/official/notice'
      preLoaderRoute: typeof OfficialNoticeIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/_layout/school-record': {
      id: '/users/_layout/school-record'
      path: '/school-record'
      fullPath: '/users/school-record'
      preLoaderRoute: typeof UsersLayoutSchoolRecordLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/users/_layout/profile': {
      id: '/users/_layout/profile'
      path: '/profile'
      fullPath: '/users/profile'
      preLoaderRoute: typeof UsersLayoutProfileLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/users/_layout/mock-exam': {
      id: '/users/_layout/mock-exam'
      path: '/mock-exam'
      fullPath: '/users/mock-exam'
      preLoaderRoute: typeof UsersLayoutMockExamLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/users/_layout/additional-file': {
      id: '/users/_layout/additional-file'
      path: '/additional-file'
      fullPath: '/users/additional-file'
      preLoaderRoute: typeof UsersLayoutAdditionalFileLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/official/notice/$postId': {
      id: '/official/notice/$postId'
      path: '/official/notice/$postId'
      fullPath: '/official/notice/$postId'
      preLoaderRoute: typeof OfficialNoticePostIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer/_layout/profile': {
      id: '/officer/_layout/profile'
      path: '/profile'
      fullPath: '/officer/profile'
      preLoaderRoute: typeof OfficerLayoutProfileLazyRouteImport
      parentRoute: typeof OfficerLayoutRoute
    }
    '/ms/_layout/subject': {
      id: '/ms/_layout/subject'
      path: '/subject'
      fullPath: '/ms/subject'
      preLoaderRoute: typeof MsLayoutSubjectLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/setuk': {
      id: '/ms/_layout/setuk'
      path: '/setuk'
      fullPath: '/ms/setuk'
      preLoaderRoute: typeof MsLayoutSetukLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/school-record': {
      id: '/ms/_layout/school-record'
      path: '/school-record'
      fullPath: '/ms/school-record'
      preLoaderRoute: typeof MsLayoutSchoolRecordLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/request': {
      id: '/ms/_layout/request'
      path: '/request'
      fullPath: '/ms/request'
      preLoaderRoute: typeof MsLayoutRequestLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/performance': {
      id: '/ms/_layout/performance'
      path: '/performance'
      fullPath: '/ms/performance'
      preLoaderRoute: typeof MsLayoutPerformanceLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/nonsul': {
      id: '/ms/_layout/nonsul'
      path: '/nonsul'
      fullPath: '/ms/nonsul'
      preLoaderRoute: typeof MsLayoutNonsulLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/kyokwa': {
      id: '/ms/_layout/kyokwa'
      path: '/kyokwa'
      fullPath: '/ms/kyokwa'
      preLoaderRoute: typeof MsLayoutKyokwaLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/jonghap': {
      id: '/ms/_layout/jonghap'
      path: '/jonghap'
      fullPath: '/ms/jonghap'
      preLoaderRoute: typeof MsLayoutJonghapLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/interest': {
      id: '/ms/_layout/interest'
      path: '/interest'
      fullPath: '/ms/interest'
      preLoaderRoute: typeof MsLayoutInterestLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/evaluation-list': {
      id: '/ms/_layout/evaluation-list'
      path: '/evaluation-list'
      fullPath: '/ms/evaluation-list'
      preLoaderRoute: typeof MsLayoutEvaluationListLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/creative-activity': {
      id: '/ms/_layout/creative-activity'
      path: '/creative-activity'
      fullPath: '/ms/creative-activity'
      preLoaderRoute: typeof MsLayoutCreativeActivityLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/comprehensive': {
      id: '/ms/_layout/comprehensive'
      path: '/comprehensive'
      fullPath: '/ms/comprehensive'
      preLoaderRoute: typeof MsLayoutComprehensiveLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/compatibility': {
      id: '/ms/_layout/compatibility'
      path: '/compatibility'
      fullPath: '/ms/compatibility'
      preLoaderRoute: typeof MsLayoutCompatibilityLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/ms/_layout/combination': {
      id: '/ms/_layout/combination'
      path: '/combination'
      fullPath: '/ms/combination'
      preLoaderRoute: typeof MsLayoutCombinationLazyRouteImport
      parentRoute: typeof MsLayoutRoute
    }
    '/mock-analysis/_layout/wrong-answers': {
      id: '/mock-analysis/_layout/wrong-answers'
      path: '/wrong-answers'
      fullPath: '/mock-analysis/wrong-answers'
      preLoaderRoute: typeof MockAnalysisLayoutWrongAnswersLazyRouteImport
      parentRoute: typeof MockAnalysisLayoutRoute
    }
    '/mock-analysis/_layout/target-university': {
      id: '/mock-analysis/_layout/target-university'
      path: '/target-university'
      fullPath: '/mock-analysis/target-university'
      preLoaderRoute: typeof MockAnalysisLayoutTargetUniversityLazyRouteImport
      parentRoute: typeof MockAnalysisLayoutRoute
    }
    '/mock-analysis/_layout/statistics': {
      id: '/mock-analysis/_layout/statistics'
      path: '/statistics'
      fullPath: '/mock-analysis/statistics'
      preLoaderRoute: typeof MockAnalysisLayoutStatisticsLazyRouteImport
      parentRoute: typeof MockAnalysisLayoutRoute
    }
    '/mock-analysis/_layout/score-input': {
      id: '/mock-analysis/_layout/score-input'
      path: '/score-input'
      fullPath: '/mock-analysis/score-input'
      preLoaderRoute: typeof MockAnalysisLayoutScoreInputLazyRouteImport
      parentRoute: typeof MockAnalysisLayoutRoute
    }
    '/mock-analysis/_layout/score-analysis': {
      id: '/mock-analysis/_layout/score-analysis'
      path: '/score-analysis'
      fullPath: '/mock-analysis/score-analysis'
      preLoaderRoute: typeof MockAnalysisLayoutScoreAnalysisLazyRouteImport
      parentRoute: typeof MockAnalysisLayoutRoute
    }
    '/mock-analysis/_layout/prediction': {
      id: '/mock-analysis/_layout/prediction'
      path: '/prediction'
      fullPath: '/mock-analysis/prediction'
      preLoaderRoute: typeof MockAnalysisLayoutPredictionLazyRouteImport
      parentRoute: typeof MockAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/subject': {
      id: '/grade-analysis/_layout/subject'
      path: '/subject'
      fullPath: '/grade-analysis/subject'
      preLoaderRoute: typeof GradeAnalysisLayoutSubjectLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/school-record': {
      id: '/grade-analysis/_layout/school-record'
      path: '/school-record'
      fullPath: '/grade-analysis/school-record'
      preLoaderRoute: typeof GradeAnalysisLayoutSchoolRecordLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/request': {
      id: '/grade-analysis/_layout/request'
      path: '/request'
      fullPath: '/grade-analysis/request'
      preLoaderRoute: typeof GradeAnalysisLayoutRequestLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/performance': {
      id: '/grade-analysis/_layout/performance'
      path: '/performance'
      fullPath: '/grade-analysis/performance'
      preLoaderRoute: typeof GradeAnalysisLayoutPerformanceLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/nonsul': {
      id: '/grade-analysis/_layout/nonsul'
      path: '/nonsul'
      fullPath: '/grade-analysis/nonsul'
      preLoaderRoute: typeof GradeAnalysisLayoutNonsulLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/evaluation-list': {
      id: '/grade-analysis/_layout/evaluation-list'
      path: '/evaluation-list'
      fullPath: '/grade-analysis/evaluation-list'
      preLoaderRoute: typeof GradeAnalysisLayoutEvaluationListLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/grade-analysis/_layout/comprehensive': {
      id: '/grade-analysis/_layout/comprehensive'
      path: '/comprehensive'
      fullPath: '/grade-analysis/comprehensive'
      preLoaderRoute: typeof GradeAnalysisLayoutComprehensiveLazyRouteImport
      parentRoute: typeof GradeAnalysisLayoutRoute
    }
    '/evaluation/_layout/request': {
      id: '/evaluation/_layout/request'
      path: '/request'
      fullPath: '/evaluation/request'
      preLoaderRoute: typeof EvaluationLayoutRequestLazyRouteImport
      parentRoute: typeof EvaluationLayoutRoute
    }
    '/evaluation/_layout/list': {
      id: '/evaluation/_layout/list'
      path: '/list'
      fullPath: '/evaluation/list'
      preLoaderRoute: typeof EvaluationLayoutListLazyRouteImport
      parentRoute: typeof EvaluationLayoutRoute
    }
    '/evaluation/_layout/compatibility': {
      id: '/evaluation/_layout/compatibility'
      path: '/compatibility'
      fullPath: '/evaluation/compatibility'
      preLoaderRoute: typeof EvaluationLayoutCompatibilityLazyRouteImport
      parentRoute: typeof EvaluationLayoutRoute
    }
    '/auth/oauth/callback': {
      id: '/auth/oauth/callback'
      path: '/auth/oauth/callback'
      fullPath: '/auth/oauth/callback'
      preLoaderRoute: typeof AuthOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/_layout/payment/': {
      id: '/users/_layout/payment/'
      path: '/payment'
      fullPath: '/users/payment'
      preLoaderRoute: typeof UsersLayoutPaymentIndexLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/officer/_layout/apply/': {
      id: '/officer/_layout/apply/'
      path: '/apply'
      fullPath: '/officer/apply'
      preLoaderRoute: typeof OfficerLayoutApplyIndexLazyRouteImport
      parentRoute: typeof OfficerLayoutRoute
    }
    '/evaluation/_layout/self/': {
      id: '/evaluation/_layout/self/'
      path: '/self'
      fullPath: '/evaluation/self'
      preLoaderRoute: typeof EvaluationLayoutSelfIndexLazyRouteImport
      parentRoute: typeof EvaluationLayoutRoute
    }
    '/users/_layout/payment/$id': {
      id: '/users/_layout/payment/$id'
      path: '/payment/$id'
      fullPath: '/users/payment/$id'
      preLoaderRoute: typeof UsersLayoutPaymentIdLazyRouteImport
      parentRoute: typeof UsersLayoutRoute
    }
    '/officer/_layout/apply/$evaluationId': {
      id: '/officer/_layout/apply/$evaluationId'
      path: '/apply/$evaluationId'
      fullPath: '/officer/apply/$evaluationId'
      preLoaderRoute: typeof OfficerLayoutApplyEvaluationIdLazyRouteImport
      parentRoute: typeof OfficerLayoutRoute
    }
  }
}

interface GradeAnalysisLayoutRouteChildren {
  GradeAnalysisLayoutComprehensiveLazyRoute: typeof GradeAnalysisLayoutComprehensiveLazyRoute
  GradeAnalysisLayoutEvaluationListLazyRoute: typeof GradeAnalysisLayoutEvaluationListLazyRoute
  GradeAnalysisLayoutNonsulLazyRoute: typeof GradeAnalysisLayoutNonsulLazyRoute
  GradeAnalysisLayoutPerformanceLazyRoute: typeof GradeAnalysisLayoutPerformanceLazyRoute
  GradeAnalysisLayoutRequestLazyRoute: typeof GradeAnalysisLayoutRequestLazyRoute
  GradeAnalysisLayoutSchoolRecordLazyRoute: typeof GradeAnalysisLayoutSchoolRecordLazyRoute
  GradeAnalysisLayoutSubjectLazyRoute: typeof GradeAnalysisLayoutSubjectLazyRoute
}

const GradeAnalysisLayoutRouteChildren: GradeAnalysisLayoutRouteChildren = {
  GradeAnalysisLayoutComprehensiveLazyRoute:
    GradeAnalysisLayoutComprehensiveLazyRoute,
  GradeAnalysisLayoutEvaluationListLazyRoute:
    GradeAnalysisLayoutEvaluationListLazyRoute,
  GradeAnalysisLayoutNonsulLazyRoute: GradeAnalysisLayoutNonsulLazyRoute,
  GradeAnalysisLayoutPerformanceLazyRoute:
    GradeAnalysisLayoutPerformanceLazyRoute,
  GradeAnalysisLayoutRequestLazyRoute: GradeAnalysisLayoutRequestLazyRoute,
  GradeAnalysisLayoutSchoolRecordLazyRoute:
    GradeAnalysisLayoutSchoolRecordLazyRoute,
  GradeAnalysisLayoutSubjectLazyRoute: GradeAnalysisLayoutSubjectLazyRoute,
}

const GradeAnalysisLayoutRouteWithChildren =
  GradeAnalysisLayoutRoute._addFileChildren(GradeAnalysisLayoutRouteChildren)

interface GradeAnalysisRouteRouteChildren {
  GradeAnalysisLayoutRoute: typeof GradeAnalysisLayoutRouteWithChildren
  GradeAnalysisIndexLazyRoute: typeof GradeAnalysisIndexLazyRoute
}

const GradeAnalysisRouteRouteChildren: GradeAnalysisRouteRouteChildren = {
  GradeAnalysisLayoutRoute: GradeAnalysisLayoutRouteWithChildren,
  GradeAnalysisIndexLazyRoute: GradeAnalysisIndexLazyRoute,
}

const GradeAnalysisRouteRouteWithChildren =
  GradeAnalysisRouteRoute._addFileChildren(GradeAnalysisRouteRouteChildren)

interface MockAnalysisLayoutRouteChildren {
  MockAnalysisLayoutPredictionLazyRoute: typeof MockAnalysisLayoutPredictionLazyRoute
  MockAnalysisLayoutScoreAnalysisLazyRoute: typeof MockAnalysisLayoutScoreAnalysisLazyRoute
  MockAnalysisLayoutScoreInputLazyRoute: typeof MockAnalysisLayoutScoreInputLazyRoute
  MockAnalysisLayoutStatisticsLazyRoute: typeof MockAnalysisLayoutStatisticsLazyRoute
  MockAnalysisLayoutTargetUniversityLazyRoute: typeof MockAnalysisLayoutTargetUniversityLazyRoute
  MockAnalysisLayoutWrongAnswersLazyRoute: typeof MockAnalysisLayoutWrongAnswersLazyRoute
}

const MockAnalysisLayoutRouteChildren: MockAnalysisLayoutRouteChildren = {
  MockAnalysisLayoutPredictionLazyRoute: MockAnalysisLayoutPredictionLazyRoute,
  MockAnalysisLayoutScoreAnalysisLazyRoute:
    MockAnalysisLayoutScoreAnalysisLazyRoute,
  MockAnalysisLayoutScoreInputLazyRoute: MockAnalysisLayoutScoreInputLazyRoute,
  MockAnalysisLayoutStatisticsLazyRoute: MockAnalysisLayoutStatisticsLazyRoute,
  MockAnalysisLayoutTargetUniversityLazyRoute:
    MockAnalysisLayoutTargetUniversityLazyRoute,
  MockAnalysisLayoutWrongAnswersLazyRoute:
    MockAnalysisLayoutWrongAnswersLazyRoute,
}

const MockAnalysisLayoutRouteWithChildren =
  MockAnalysisLayoutRoute._addFileChildren(MockAnalysisLayoutRouteChildren)

interface MockAnalysisRouteRouteChildren {
  MockAnalysisLayoutRoute: typeof MockAnalysisLayoutRouteWithChildren
}

const MockAnalysisRouteRouteChildren: MockAnalysisRouteRouteChildren = {
  MockAnalysisLayoutRoute: MockAnalysisLayoutRouteWithChildren,
}

const MockAnalysisRouteRouteWithChildren =
  MockAnalysisRouteRoute._addFileChildren(MockAnalysisRouteRouteChildren)

interface MsLayoutRouteChildren {
  MsLayoutCombinationLazyRoute: typeof MsLayoutCombinationLazyRoute
  MsLayoutCompatibilityLazyRoute: typeof MsLayoutCompatibilityLazyRoute
  MsLayoutComprehensiveLazyRoute: typeof MsLayoutComprehensiveLazyRoute
  MsLayoutCreativeActivityLazyRoute: typeof MsLayoutCreativeActivityLazyRoute
  MsLayoutEvaluationListLazyRoute: typeof MsLayoutEvaluationListLazyRoute
  MsLayoutInterestLazyRoute: typeof MsLayoutInterestLazyRoute
  MsLayoutJonghapLazyRoute: typeof MsLayoutJonghapLazyRoute
  MsLayoutKyokwaLazyRoute: typeof MsLayoutKyokwaLazyRoute
  MsLayoutNonsulLazyRoute: typeof MsLayoutNonsulLazyRoute
  MsLayoutPerformanceLazyRoute: typeof MsLayoutPerformanceLazyRoute
  MsLayoutRequestLazyRoute: typeof MsLayoutRequestLazyRoute
  MsLayoutSchoolRecordLazyRoute: typeof MsLayoutSchoolRecordLazyRoute
  MsLayoutSetukLazyRoute: typeof MsLayoutSetukLazyRoute
  MsLayoutSubjectLazyRoute: typeof MsLayoutSubjectLazyRoute
}

const MsLayoutRouteChildren: MsLayoutRouteChildren = {
  MsLayoutCombinationLazyRoute: MsLayoutCombinationLazyRoute,
  MsLayoutCompatibilityLazyRoute: MsLayoutCompatibilityLazyRoute,
  MsLayoutComprehensiveLazyRoute: MsLayoutComprehensiveLazyRoute,
  MsLayoutCreativeActivityLazyRoute: MsLayoutCreativeActivityLazyRoute,
  MsLayoutEvaluationListLazyRoute: MsLayoutEvaluationListLazyRoute,
  MsLayoutInterestLazyRoute: MsLayoutInterestLazyRoute,
  MsLayoutJonghapLazyRoute: MsLayoutJonghapLazyRoute,
  MsLayoutKyokwaLazyRoute: MsLayoutKyokwaLazyRoute,
  MsLayoutNonsulLazyRoute: MsLayoutNonsulLazyRoute,
  MsLayoutPerformanceLazyRoute: MsLayoutPerformanceLazyRoute,
  MsLayoutRequestLazyRoute: MsLayoutRequestLazyRoute,
  MsLayoutSchoolRecordLazyRoute: MsLayoutSchoolRecordLazyRoute,
  MsLayoutSetukLazyRoute: MsLayoutSetukLazyRoute,
  MsLayoutSubjectLazyRoute: MsLayoutSubjectLazyRoute,
}

const MsLayoutRouteWithChildren = MsLayoutRoute._addFileChildren(
  MsLayoutRouteChildren,
)

interface MsRouteRouteChildren {
  MsLayoutRoute: typeof MsLayoutRouteWithChildren
  MsIndexLazyRoute: typeof MsIndexLazyRoute
}

const MsRouteRouteChildren: MsRouteRouteChildren = {
  MsLayoutRoute: MsLayoutRouteWithChildren,
  MsIndexLazyRoute: MsIndexLazyRoute,
}

const MsRouteRouteWithChildren =
  MsRouteRoute._addFileChildren(MsRouteRouteChildren)

interface ScoreAnalysisRouteRouteChildren {
  ScoreAnalysisIndexLazyRoute: typeof ScoreAnalysisIndexLazyRoute
}

const ScoreAnalysisRouteRouteChildren: ScoreAnalysisRouteRouteChildren = {
  ScoreAnalysisIndexLazyRoute: ScoreAnalysisIndexLazyRoute,
}

const ScoreAnalysisRouteRouteWithChildren =
  ScoreAnalysisRouteRoute._addFileChildren(ScoreAnalysisRouteRouteChildren)

interface TryRouteRouteChildren {
  TryIndexLazyRoute: typeof TryIndexLazyRoute
}

const TryRouteRouteChildren: TryRouteRouteChildren = {
  TryIndexLazyRoute: TryIndexLazyRoute,
}

const TryRouteRouteWithChildren = TryRouteRoute._addFileChildren(
  TryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GradeAnalysisRouteRoute: GradeAnalysisRouteRouteWithChildren,
  MockAnalysisRouteRoute: MockAnalysisRouteRouteWithChildren,
  MsRouteRoute: MsRouteRouteWithChildren,
  ScoreAnalysisRouteRoute: ScoreAnalysisRouteRouteWithChildren,
  TryRouteRoute: TryRouteRouteWithChildren,
  H1Route: H1Route,
  H2Route: H2Route,
  H3Route: H3Route,
  H4Route: H4Route,
  PricingRoute: PricingRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  ExploreAdmissionRoute: ExploreAdmissionRoute,
  ExploreRecruitmentUnitRoute: ExploreRecruitmentUnitRoute,
  ExploreUniversityRoute: ExploreUniversityRoute,
  OrderProductIdRoute: OrderProductIdRoute,
  TestAuthMeRoute: TestAuthMeRoute,
  TestLoginDebugRoute: TestLoginDebugRoute,
  naverRedirectLazyRoute: naverRedirectLazyRoute,
  AnalysisPerformanceLazyRoute: AnalysisPerformanceLazyRoute,
  ExplainPrivacyLazyRoute: ExplainPrivacyLazyRoute,
  ExplainRefundLazyRoute: ExplainRefundLazyRoute,
  ExplainServiceLazyRoute: ExplainServiceLazyRoute,
  ExploreSusiJonghapLazyRoute: ExploreSusiJonghapLazyRoute,
  ExploreSusiKyokwaLazyRoute: ExploreSusiKyokwaLazyRoute,
  OfficialFaqLazyRoute: OfficialFaqLazyRoute,
  OfficialGuideLazyRoute: OfficialGuideLazyRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  AnalysisIndexLazyRoute: AnalysisIndexLazyRoute,
  AuthOauthCallbackRoute: AuthOauthCallbackRoute,
  OfficialNoticePostIdLazyRoute: OfficialNoticePostIdLazyRoute,
  OfficialNoticeIndexLazyRoute: OfficialNoticeIndexLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
