import { UserSchoolRecord } from '@/apis/hooks/use-school-record';

export const mockSchoolRecord: UserSchoolRecord = {
  subjects: [
    {
      grade: 1,
      semester: 1,
      subjectName: '국어',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 2,
      note: '',
      subjectGroup: {
        id: 1,
        code: 'HH1',
        name: '국어',
      },
    },
    {
      grade: 1,
      semester: 1,
      subjectName: '영어',
      units: 5,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 4,
      note: '',
      subjectGroup: {
        id: 3,
        code: 'HH3',
        name: '영어',
      },
    },
    {
      grade: 1,
      semester: 1,
      subjectName: '한국사',
      units: 3,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 1,
      note: '',
      subjectGroup: {
        id: 7,
        code: 'HH7',
        name: '한국사',
      },
    },
    {
      grade: 1,
      semester: 1,
      subjectName: '통합사회',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 1,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 1,
      semester: 1,
      subjectName: '수학',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'C',
      numberOfStudents: 0,
      gradeRank: 4,
      note: '',
      subjectGroup: {
        id: 2,
        code: 'HH2',
        name: '수학',
      },
    },
    {
      grade: 1,
      semester: 1,
      subjectName: '통합과학',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 5,
        code: 'HH5',
        name: '과학',
      },
    },
    {
      grade: 1,
      semester: 2,
      subjectName: '한국사',
      units: 3,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 1,
      note: '',
      subjectGroup: {
        id: 7,
        code: 'HH7',
        name: '한국사',
      },
    },
    {
      grade: 1,
      semester: 2,
      subjectName: '국어',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 1,
        code: 'HH1',
        name: '국어',
      },
    },
    {
      grade: 1,
      semester: 2,
      subjectName: '영어',
      units: 5,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 3,
        code: 'HH3',
        name: '영어',
      },
    },
    {
      grade: 1,
      semester: 2,
      subjectName: '통합사회',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 1,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 1,
      semester: 2,
      subjectName: '수학',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'D',
      numberOfStudents: 0,
      gradeRank: 4,
      note: '',
      subjectGroup: {
        id: 2,
        code: 'HH2',
        name: '수학',
      },
    },
    {
      grade: 1,
      semester: 2,
      subjectName: '통합과학',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 5,
        code: 'HH5',
        name: '과학',
      },
    },
    {
      grade: 2,
      semester: 1,
      subjectName: '독서',
      units: 5,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 1,
        code: 'HH1',
        name: '국어',
      },
    },
    {
      grade: 2,
      semester: 1,
      subjectName: '영어Ⅰ',
      units: 5,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 3,
        code: 'HH3',
        name: '영어',
      },
    },
    {
      grade: 2,
      semester: 1,
      subjectName: '한국지리',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 2,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 2,
      semester: 1,
      subjectName: '동아시아사',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 1,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 2,
      semester: 1,
      subjectName: '생활과 윤리',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 2,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 2,
      semester: 1,
      subjectName: '수학Ⅰ',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'C',
      numberOfStudents: 0,
      gradeRank: 4,
      note: '',
      subjectGroup: {
        id: 2,
        code: 'HH2',
        name: '수학',
      },
    },
    {
      grade: 2,
      semester: 1,
      subjectName: '물리학Ⅰ',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 1,
      note: '',
      subjectGroup: {
        id: 5,
        code: 'HH5',
        name: '과학',
      },
    },
    {
      grade: 2,
      semester: 2,
      subjectName: '문학',
      units: 5,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 2,
      note: '',
      subjectGroup: {
        id: 1,
        code: 'HH1',
        name: '국어',
      },
    },
    {
      grade: 2,
      semester: 2,
      subjectName: '영어 회화',
      units: 5,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'C',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 3,
        code: 'HH3',
        name: '영어',
      },
    },
    {
      grade: 2,
      semester: 2,
      subjectName: '한국지리',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 2,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 2,
      semester: 2,
      subjectName: '동아시아사',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 1,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 2,
      semester: 2,
      subjectName: '생활과 윤리',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 2,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 2,
      semester: 2,
      subjectName: '미적분',
      units: 4,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 2,
        code: 'HH2',
        name: '수학',
      },
    },
    {
      grade: 2,
      semester: 2,
      subjectName: '물리학Ⅰ',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'A',
      numberOfStudents: 0,
      gradeRank: 1,
      note: '',
      subjectGroup: {
        id: 5,
        code: 'HH5',
        name: '과학',
      },
    },
    {
      grade: 3,
      semester: 1,
      subjectName: '독서',
      units: 3,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 1,
        code: 'HH1',
        name: '국어',
      },
    },
    {
      grade: 3,
      semester: 1,
      subjectName: '윤리와 사상',
      units: 2,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 3,
      semester: 1,
      subjectName: '한국지리',
      units: 1,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 3,
      semester: 1,
      subjectName: '정치와 법',
      units: 3,
      score: 0,
      average: 0,
      standardDeviation: 0,
      achievement: 'B',
      numberOfStudents: 0,
      gradeRank: 3,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
  ],
  selectSubjects: [
    {
      grade: 2,
      semester: 1,
      subjectName: '여행지리',
      units: 2,
      score: 0,
      average: 0,
      achievement: 'A',
      numberOfStudents: 0,
      achievementRatioA: 0,
      achievementRatioB: 0,
      achievementRatioC: 0,
      note: '',
      subjectGroup: {
        id: 4,
        code: 'HH4',
        name: '사회(역사/도덕포함)',
      },
    },
    {
      grade: 2,
      semester: 2,
      subjectName: '기하',
      units: 4,
      score: 0,
      average: 0,
      achievement: 'A',
      numberOfStudents: 0,
      achievementRatioA: 0,
      achievementRatioB: 0,
      achievementRatioC: 0,
      note: '',
      subjectGroup: {
        id: 2,
        code: 'HH2',
        name: '수학',
      },
    },
    {
      grade: 3,
      semester: 1,
      subjectName: '실용 영어',
      units: 3,
      score: 0,
      average: 0,
      achievement: 'B',
      numberOfStudents: 0,
      achievementRatioA: 0,
      achievementRatioB: 0,
      achievementRatioC: 0,
      note: '',
      subjectGroup: {
        id: 3,
        code: 'HH3',
        name: '영어',
      },
    },
    {
      grade: 3,
      semester: 1,
      subjectName: '실용 수학',
      units: 3,
      score: 0,
      average: 0,
      achievement: 'C',
      numberOfStudents: 0,
      achievementRatioA: 0,
      achievementRatioB: 0,
      achievementRatioC: 0,
      note: '',
      subjectGroup: {
        id: 2,
        code: 'HH2',
        name: '수학',
      },
    },
    {
      grade: 3,
      semester: 1,
      subjectName: '수학과제 탐구',
      units: 3,
      score: 0,
      average: 0,
      achievement: 'C',
      numberOfStudents: 0,
      achievementRatioA: 0,
      achievementRatioB: 0,
      achievementRatioC: 0,
      note: '',
      subjectGroup: {
        id: 2,
        code: 'HH2',
        name: '수학',
      },
    },
    {
      grade: 3,
      semester: 1,
      subjectName: '물리학Ⅱ',
      units: 3,
      score: 0,
      average: 0,
      achievement: 'A',
      numberOfStudents: 0,
      achievementRatioA: 0,
      achievementRatioB: 0,
      achievementRatioC: 0,
      note: '',
      subjectGroup: {
        id: 5,
        code: 'HH5',
        name: '과학',
      },
    },
  ],
  sportArts: [],
  attendances: [
    {
      grade: 1,
      totalDays: 0,
      absenceSick: 0,
      absenceUnexcused: 0,
      absenceEtc: 0,
      tardySick: 0,
      tardyUnexcused: 0,
      tardyEtc: 0,
      leaveSick: 0,
      leaveUnexcused: 0,
      leaveEtc: 0,
      cutSick: 0,
      cutUnexcused: 0,
      cutEtc: 0,
      note: '',
    },
    {
      grade: 2,
      totalDays: 0,
      absenceSick: 0,
      absenceUnexcused: 0,
      absenceEtc: 0,
      tardySick: 0,
      tardyUnexcused: 0,
      tardyEtc: 0,
      leaveSick: 0,
      leaveUnexcused: 0,
      leaveEtc: 0,
      cutSick: 0,
      cutUnexcused: 0,
      cutEtc: 0,
      note: '',
    },
    {
      grade: 3,
      totalDays: 0,
      absenceSick: 0,
      absenceUnexcused: 0,
      absenceEtc: 0,
      tardySick: 0,
      tardyUnexcused: 0,
      tardyEtc: 0,
      leaveSick: 0,
      leaveUnexcused: 0,
      leaveEtc: 0,
      cutSick: 0,
      cutUnexcused: 0,
      cutEtc: 0,
      note: '',
    },
  ],
  creativeActivities: [],
  behaviorOpinions: [],
};
